### ISSUE TITLE
Proper trackpad gestures

### ISSUE THREAD

**Issue by therealmarv** [jurplel/qView#170]
I'm on a mac and most often I use the trackpad.
I really like this picture viewer and it is nearly perfect. However when using a trackpad the experience is not perfect (yet).

I use pinch and zoom to zoom in and out and the two finger scrolling natural behaviour would be moving the image (like click and hold and move the cursor).

Currently scrolling gives me zoom in and out and pinch and zoom is not working.

Just for reference: Xee3 has an option to switch between mouse mode and trackpad mode. A similar option would be very appreciated :)

![image](https://user-images.githubusercontent.com/1050582/46603626-e5703580-caf3-11e8-9e98-3398245f7d5c.png)

Great work overall!

**Comment by jeep70** [comment]
I'll see what I can do.

**Comment by jeep70** [comment]
Please try this [version](https://github.com/jeep70/qView/files/2475081/qView.zip).
I don't have any capable hardware to test on, so I have no idea how/how well this works. It would be great if you could record a video or something. Thanks

**Comment by therealmarv** [comment]
It's better than nothing. Currently it's not smooth in comparison to Xee. It's more stuttering and does not feel like a normal "mac-ish" pinch and zoom. I'm currently traveling but I can try to record a video on Wednesday.

**Comment by jeep70** [comment]
Do you mean that it is not perfectly smooth like macOS's preview application, or that the pinch to zooming doesn't feel like it matches what your fingers are doing? I wasn't planning on having 1:1 smooth zooming like Preview.app but I might be able to pull it off

**Comment by therealmarv** [comment]
yes right. It does not feel like the zooming in preview.app as you describe. btw: I think this behaviour is not only for Mac interesting. Many Windows machines also support pinch and zoom nowadays.

**Comment by jurplel** [comment]
I don't plan on implementing that full resolution zoom like in the preview app. The best you can do is reduce the scale factor to 1% and that will be pretty close. I need to know if the touchpad gestures feel like they have the correct distances, etc as they are now. Also, the gestures should work for not just scaling, but also rotation and movement (all using pinch-style gestures). Please test and report back when you can, thanks.

**Comment by therealmarv** [comment]
Hi, I've retested. For me this behaviour is a deal breaker (but this is only my opinion) because this app does not feel like an app should behave on a Mac. Zoom scaling should be reduced... zooming in and out is too much in too wide steps in either direct (it should be at least 50% less, maybe even more). Rotation works but without animation it feels a littlebit clunky (but this is still okay for me).
Moving with two fingers on trackpad does not work.

Sorry for beeing so harsh but I think a picture viewer which does not feel like the preview app feels like a workaround for me because Preview and Xee set the standard on this platform.

**Comment by sn0wyfall** [comment]
I totally feel. I think for an app like qview, being smooth is one of the main things I'd want to use it for. Since it didn't have that I didn't want to use it. However, I definitely probably will start using it again if it has a smooth interface. Thanks a lot for noting this, @jurplel

**Comment by jurplel** [comment]
I don't know if I mentioned this, but there are two reasons support is bad right now:
- Zooming is coded with distinct steps in mind
- I have not had a trackpad to test on.

I just recently got access to a gesture-supporting trackpad so I was able to confirm the poor quality of my blind implementation. This will definitely be improved upon at some point but I am working on some other things first.

**Comment by sn0wyfall** [comment]
No worries, I understand! Take your time, I know how long developing takes, especially when you have other things to do. In any case, qview as it is is a great piece of software, and I'm sure that there are many out there who aren't spoiled by macOS's native smoothness who appreciate this. 

As a matter of fact, I think this is a worthy competitor of [Xee](https://theunarchiver.com/xee), and in fact I think it's way better. I'm sure people would flock over from Xee if they had heard about qview. 

That's cool that you've developed this without a trackpad though! :)

**Comment by timea-techgirl** [comment]
Pinching scrolls the image instead of zoom. I hold Ctrl once and let go of it without releasing the pinch and it zooms correctly.

I think holding Ctrl and pinch must scroll. Normal pinch must zoom.

This is my observation on my Dell windows laptop.

**Comment by jurplel** [comment]
There will be some basic improvements to this in 5.0, see https://github.com/jurplel/qView/commit/34437376886a6fada375b90498d8b3d4d6dc16d6
