### ISSUE TITLE
Keyboard shortcut customization

### ISSUE THREAD

**Issue by kupiqu** [jurplel/qView#180]
As mentioned before I like using qView as an image "preview" application. I set a kservice5 in dolphin to trigger it from images, and with that purpose in mind, I wish to use the ESC key to be an alternative to Ctrl+Q to quit the application. But, if I'm not wrong, ESC is currently used to exit the full screen mode.

Do you think you could integrate qView keyboard shortcuts in KDE's system settings so users can set their own preference?

**Comment by jurplel** [comment]
Would making keyboard shortcuts customizable be satisfactory? KDE's system settings are platform-specific and I believe for global shortcuts (regardless of application focus)

**Comment by kupiqu** [comment]
Sounds great, thank you.

**Comment by AndydeCleyre** [comment]
Just checking in to note that I came here because I'm missingr this exact shortcut (esc to quit).

**Comment by tabakisp** [comment]
Thanks for an awesome app. I would totally love to be able to customize the keyboard shortcuts. In my case, I was looking to change Next File from right arrow to Wheel Up or Down. Please let us choose our own shortcuts. Again, thanks for everything.

**Comment by williamd1k0** [comment]
I just found this project and this looks really promising!
I've been using [qimgv](https://github.com/easymodo/qimgv) on Windows and GNU/Linux so far and it has customizable shortcuts. I just need a shortcut to switch between "original size" and "fit window" using the middle mouse click.
