### ISSUE TITLE
qView website is down

### ISSUE THREAD

**Issue by CreamyCookie** [jurplel/qView#189]
Maybe this is temporary but https://interverse.tk/qview/ seems to be down

**Comment by jurplel** [comment]
Update: the reason they give is "abuse" (probably made up) and have released the domain back for registration
![screenshot-2018-12-14-12 34 04](https://user-images.githubusercontent.com/10716694/50018333-efebf700-ff9c-11e8-9279-72f4df2f023c.png)

Hilarious...
I refuse to pay out of principle but I think they will put it back to free at some point. (based on the fact that they have done this to me before after it expired)

**Comment by moll** [comment]
I don't think it's a smart move to host any software, open source or not, on domains you don't own. What's preventing someone from grabbing the domain now, putting some malware up on it and screwing a few trusting souls before you remove all the links to the site?
