### ISSUE TITLE
Error: File does not exist

### ISSUE THREAD

**Issue by Klammeraffee** [jurplel/qView#191]
Whenever a file is opened from file explorer, qView opens with error message:
Error: File does not exist.

This is true for every single file. I cannot open any file from file explorer with qView.

However, when I drag & drop a file into qView it works fine and it can also cycle pictures in a folder with arrow keys - as long as I open a file with drag & drop.

![deepinscreenshot_select-area_20190103215852](https://user-images.githubusercontent.com/46358212/50661249-cb36de00-0fa2-11e9-8125-7eaeff6423b6.png)

OS used:
Manjaro Linux Deepin 15.8

qView version: latest 1.0-2

I am new to github, if you need any logfiles, please give me the commands to retrieve them :) 
Thanks for your help and newbie understanding.

**Comment by jurplel** [comment]
The issue was that Manjaro Linux Deepin's file manager for some reason passes the file path as `file://path/to/your/file.png` instead of `/path/to/your/file.png`, and qView didn't sanitize inputs enough to prepare for that. I fixed it by using this setup to sanitize inputs:

```cpp
QUrl sanitaryUrl = QUrl(fileName);
sanitaryUrl.setScheme(QString());
QString sanitaryString = QUrl::fromPercentEncoding(sanitaryUrl.toEncoded());
```
