### ISSUE TITLE
background color applied to pop-up windows

### ISSUE THREAD

**Issue by kupiqu** [jurplel/qView#197]
this is minor, but for enhanced consistency, I'd propose that the background color could also be applied to `help > about/welcome` pop-up windows.

the only issue with this is that light background colors may make the current white color font invisible, so this change would also require the font color to be adjusted between dark/light colors to reverse the overall looking of the background (light/dark, respectively).

this can be easily done by converting the background color to grayscale and setting a conditional threshold. Something like:

```
QColor fontColor;
if ( qGray(backgroundColor.rgb()) > 128 )
  fontColor = darkColor;
else
  fontColor = lightColor;
```

thanks for considering...

**Comment by jurplel** [comment]
I appreciate the feedback, but the color of the about and welcome pages is intentionally static. It represents qView's "branding" as seen on the website. I actually considered doing this when I was first working on this, and I see where you are coming from, but I would personally prefer to keep it this way. Sorry for the delay in responding, I had a busy couple of days.

**Comment by kupiqu** [comment]
no problem :)
