### ISSUE TITLE
AppImage bundle

### ISSUE THREAD

**Issue by koutoftimer** [jurplel/qView#212]
Have you thought about [AppImage][appimage] for distribution under GNU\Linux ?

   [appimage]: https://appimage.org/

**Comment by jurplel** [comment]
I actually was originally planning on releasing an AppImage along with 2.0, but I experienced some difficulties trying to make one. I tried to get it to automatically build on the OpenSuse Build Service, but I really don't know what I'm doing and I was unable to get it to build. I was multiple days into it at that point, so I decided to just drop it for the time being. If I could get it to work on the OpenSuse Build Service, I'd love to distribute an AppImage.

**Comment by jurplel** [comment]
AppImages are now built on Azure Pipelines and will be available with future releases. If you have any suggestions to improve the deployment of AppImages, I would love to hear them.
