### ISSUE TITLE
HDR support

### ISSUE THREAD

**Issue by dbarkar** [jurplel/qView#214]
Hey guys, thanks for the great software!
Do you have plans to add support for viewing HDR files? That would be great!
As I can see, it should support HDR displays (if available) and intelligent conversion (with customizable exposure, etc) for SDR displays.

**Comment by jurplel** [comment]
I believe that would actually be really difficult. As it stands, qView uses the built-in Qt classes for everything. To take a look at some of the challenges of implementing HDR support in Qt, take a look at [this blog post](https://krita.org/en/item/krita-4-2-0-the-first-painting-application-to-bring-hdr-support-to-windows/). I don't think this is going to be feasible unless Qt officially supports it. 

Thank you for the suggestion!
