### ISSUE TITLE
Screen scaling support

### ISSUE THREAD

**Issue by glesik** [jurplel/qView#217]
I use KDE with screen scaling set to 2 in monitor settings (4k/HiDPI). Smaller images are rendered twice the actual size in qView even when "original size" is selected:

![image](https://user-images.githubusercontent.com/1032430/60004751-d88d7500-9675-11e9-9692-9e844557a332.png)

Setting `QT_SCREEN_SCALE_FACTORS=1` makes images display correctly, but menu icons and widgets are two times smaller than normal.

**Comment by jurplel** [comment]
Try dadb594 on your side to make sure it's working okay, or if any other issues have presented.

**Comment by glesik** [comment]
Fantastic, thanks! Hi-res images are now crisp and nice, no issues so far.
