### ISSUE TITLE
Can we integrate qview in Web browser

### ISSUE THREAD

**Issue by kamidehlvi** [jurplel/qView#227]
hi,
Indeed a good work, I am in the process of developing an Image Processing and document scanning application.  I am searching for an image viewer that can integrate with a web browser and show thumbnails and full images etc on user request. is qView provides these facilities, please?

**Comment by jurplel** [comment]
I'm sorry, I can't understand what you are asking.

**Comment by kamidehlvi** [comment]
it is simple can we use qview in a web page html, jsp etc

**Comment by jurplel** [comment]
Um, I'm still not entirely sure what you mean, but qView is a GUI program that use's Qt's built in libraries for pretty much everything. I don't know what you're trying to do exactly, but I don't think qView is what you're looking for.
