### ISSUE TITLE
Crashing when opening files from Finder

### ISSUE THREAD

**Issue by shape55** [jurplel/qView#228]
Using 10.12.6, if I double click files in the Finder, it will frequently crash as it attempts to open them in qView.  When I reopen the app, any images I had open do not reopen like they do in other apps – the saved state is not recalled.

The app is unusable for me b/c I can't ever open more than 2-3 files before it crashes.  The issue seems to happen if it tries to open more than one file at a time.

Here's the crash report:
https://pastebin.com/hwYN7xGS

**Comment by jurplel** [comment]
Yeah, I'm really sorry about that. I found that bug recently, so it's already fixed in qView 3.0 (#222). I didn't come across that bug in testing before I released 2.0. Very unprofessional, sorry again.

**Comment by shape55** [comment]
Oh ok, no problem.  Is there a beta version for qView 3 I could try in the mean time?

**Comment by jurplel** [comment]
Here, I built you one.
[qView.app.zip](https://github.com/jurplel/qView/files/3521979/qView.app.zip)

**Comment by shape55** [comment]
Awesome – thanks!  Yeah, this problem is no longer occurring on my end.

Are the open images from the previous session not supposed to re-open automatically?  Afaik, w/ all other Mac apps this is automatic when the option to "Close windows…" is unchecked in the General Preferences.  When I quit and relaunch qView, all the images I had open do not restore to their previously open state.

https://support.apple.com/en-us/HT204005

• "When you open and quit an app"
When you open an app, it automatically re-opens the windows you were working with the last time you quit the app.

**Comment by jurplel** [comment]
I haven't programmed native macOS applications before, but I think that's something that's handled automatically when you write code for mac (using [this](https://developer.apple.com/documentation/appkit/nswindow/1526255-restorable) probably)

qView would probably fall under this:
![image](https://user-images.githubusercontent.com/10716694/63387701-253eb500-c374-11e9-985d-e0a5c0fcb11f.png)

And unfortunately that functionality doesn't exist right now in qView. I will open a separate issue for later, though.

**Comment by shape55** [comment]
Sounds good – thanks.  Unfortunately, I have no coding knowledge so I cannot be of help in the matter.

**Comment by jurplel** [comment]
No problem, thanks for the suggestion!

**Comment by shape55** [comment]
My pleasure...  On a similar note, have you already considered adding the standard "Window" menu to the top toolbar (between Tools & Help) that shows the currently opened files?

**Comment by jurplel** [comment]
Good ideas, I'll definitely look into it.

**Comment by shape55** [comment]
Great – thanks
