### ISSUE TITLE
Option to remove or not populate "recent" list

### ISSUE THREAD

**Issue by Candlemass** [jurplel/qView#231]
For reasons of privacy an option to either remove the menu completely or at minimum not populate the list if chosen since this acts essentially as a log.

Other then that keep up the great work. 

Cheers.

**Comment by jurplel** [comment]
Sure thing.

**Comment by Candlemass** [comment]
Cheers.

Is there a release date for version 3.0?

**Comment by jurplel** [comment]
Within a week, hopefully.

**Comment by Candlemass** [comment]
Any update on version 3.0?

Thanks.

**Comment by jurplel** [comment]
Sorry, I just started my first semester of college and the workload has left me with no spare time for weeks. I am currently planning on getting some work done this weekend.
