### ISSUE TITLE
[macOS] add "Close Window" function & don't quit when the last window is closed

### ISSUE THREAD

**Issue by ulyssesric** [jurplel/qView#232]
If you open a 2nd image when the 1st image is already displayed, qView will display newly added image in a new window. But there is no any shortcut or menu item to close window; the only way to clean up the clutter is manually click the close-window button in the window title bar with mouse cursor. It's extremely inefficient.

Conventionally, in a macOS apps that you can press CMD+W to close the front most window / tab and SHIFT+CMD+W to close all windows. And when the last window is closed the app won't automatically quit itself, which can be added as a user choosable preference settings. Otherwise, open all images in the same window and don't create new one.

**Comment by jurplel** [comment]
I'll definitely add all of the keyboard shortcuts, but the app not closing with the last window might be a little difficult. I'll probably try to add it anyway. Thanks for the suggestion!

**Comment by jurplel** [comment]
I've added the cmd+w function now, but keeping the program open when no windows are open will require a lot of very involved work, and im not sure it would be possible to do it without compromises. I've moved it to https://github.com/jurplel/qView/issues/243 for now.
