### ISSUE TITLE
WEBM viewer and play it just like GIF

### ISSUE THREAD

**Issue by alionar** [jurplel/qView#238]
So for v3.0 i want to ask

Is it possible to add new feature like support WEBM gallery viewer and playing it as GIF Format?

Thanks

**Comment by jurplel** [comment]
I do not plan on implementing this in the near future—This will require implementing functions of a video player into qView, which will increase bloat and complexity significantly. I will keep it open for the future though. Thank you for your suggestion!

**Comment by alionar** [comment]
ok thank you for your response :)

**Comment by jurplel** [comment]
You're welcome!

**Comment by Hrxn** [comment]
@alionar You could try this one here: https://github.com/easymodo/qimgv
