### ISSUE TITLE
Option to disable zooming "towards the cursor"

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#239]

**Comment by r57zone** [comment]
Cool, thanks. When will the binaries be updated?

**Comment by jurplel** [comment]
For what operating system? I am making the binaries manually at the moment.

**Comment by r57zone** [comment]
For Windows 10 32 bit it would be great. Thanks.

**Comment by jurplel** [comment]
[qview.zip](https://github.com/jurplel/qView/files/3892473/qview.zip)
Here you go, apologies for the delay
