### ISSUE TITLE
Add pdf support

### ISSUE THREAD

**Issue by joaoponceleao** [jurplel/qView#241]
Would be great to have pdf support.

This includes pdf and svg (and possibly illustrator, etc).
The most pressing one would be pdf. It is a common file format (vector or raster based) for gis and design app exports.

**Comment by jurplel** [comment]
SVG is already supported. I will look into pdf for the future, but no promises.

**Comment by joaoponceleao** [comment]
Thank you.
I was particularly referring to single page pdfs, which might make things easier. Qgis and matplotlib users usually export maps/plots to pdf or raster file formats. Will look into svg as an alternative though.

**Comment by PlavorSeol** [comment]
I disagree - qView is an _image_ viewer, not PDF document viewer.

**Comment by joaoponceleao** [comment]
Obviously it is up to the author and users.
But just to make it clear, I am referring here to single-page pdf images, not multi-page documents.
These are standard outputs for vector images (particularly matplotlib for graphs, and gis for maps) for a variety of reasons (metadata, raster and vector in one format).

**Comment by kupiqu** [comment]
I (would like to) use qView as a document previewer, and this would be so great for that purpose

**Comment by joaoponceleao** [comment]
That might be a slightly different feature request kupiqu. Adding support for previews of single page (or only the first page) of a pdf should be relatively straightforward by simply converting that page to a supported raster format and keeping it in cache. Multi page previews (a la quicklook on mac) would be more work and also require changes to the ui.

**Comment by kupiqu** [comment]
> That might be a slightly different feature request kupiqu. Adding support for previews of single page (or only the first page) of a pdf should be relatively straightforward by simply converting that page to a supported raster format and keeping it in cache. Multi page previews (a la quicklook on mac) would be more work and also require changes to the ui.

Having a preview of the whole pdf would be nice, but just the first page might suffice as a preview, moreover once #164 is implemented. Easy and fast preview of PDF files in a folder to then open selected ones in e.g., Okular...

**Comment by joaoponceleao** [comment]
Yes. That sounds good.

**Comment by kupiqu** [comment]
> Obviously it is up to the author and users.
> But just to make it clear, I am referring here to single-page pdf images, not multi-page documents.
> These are standard outputs for vector images (particularly matplotlib for graphs, and gis for maps) for a variety of reasons (metadata, raster and vector in one format).

And btw, I totally second this too. Image figures in latex documents are frequently done in vectorized pdf format so they scale properly, and it would be nice that qViem would support this.

However, instead of rendering the pdf first page, wouldn't be possible to use poopler? This would perhaps make implementation (1) more straightforward, (2) zoom up nicely without looking blurry, and (3) would allow previewing multi-page pdfs (although the latter I understand is not the main purpose here)

**Comment by jurplel** [comment]
I am very hesitant to add external dependencies, as qView is meant to remain as light as possible. I will certainly look into this for the next version, at least the single page support but possibly a solution for turning through different pages as well. Thank you for your suggestions!

**Comment by kupiqu** [comment]
> I am very hesitant to add external dependencies, as qView is meant to remain as light as possible. I will certainly look into this for the next version, at least the single page support but possibly a solution for turning through different pages as well. Thank you for your suggestions!

Excellent, thank you

**Comment by jurplel** [comment]
I can't say I'm planning to add this at the present because PDF will require a dependency. PDF viewing will also be so different it will likely require a completely new code pipeline. Closing for the moment but may revisit one day. Thank you for your suggestion.
