### ISSUE TITLE
Delete Suport

### ISSUE THREAD

**Issue by epiller** [jurplel/qView#244]
Thank you **so** much @jurplel for making this app. I've installed dozens of photo viewing utilities and this is definitely the one I plan to keep on using. 
There's just one thing I'd really love to be able to do, and it's to delete photos (using Command + Delete). 
It's a pretty trivial thing, but when you're browsing hundreds of photos from a recent camera transfer, it would help immensely to be able to delete them on-the-go.
Now, I've never developed MacOS apps, so this is just my suggestion that I'd appreciate the hell out of if it happened, but it's also perfectly fine if it's not possible. It's a free open-source app and I've got nothing but respect for your effort on developing this app. Cheers man.

**Comment by jurplel** [comment]
Hi! I am really glad you've found my program useful, it means a lot.
The delete function is already planned for the future. It is easy in theory when using native app functions (if this was a native windows app, native macOS app, or used kde framework for example), but it is designed to be totally cross-platform, which complicates things somewhat.
Existing issue: https://github.com/jurplel/qView/issues/210

**Comment by epiller** [comment]
Ah, I understand. Well, I guess I can hope it'll happen some day :)
All the best!

**Comment by jurplel** [comment]
It certainly will!

**Comment by cyclism6486** [comment]
Are we any closer to this feature on Mac?  Or allowing us to set a shortcut for it in preferences?  I'm looking for a fast image viewer to replace my old 32-bit one (JustLooking - which has been my workhorse for years). qView fits my workflow requirements in every way except not being able to delete the file from the image viewer by hitting the "delete" key.  Thanks!

**Comment by jurplel** [comment]
I think it is already working for mac on the trash branch. I will be fully integrating trash support right after open with support.

**Comment by cyclism6486** [comment]
Not sure if I fully understand your reply, but it sounds like good news....this feature may be integrated soon?

**Comment by jurplel** [comment]
What I mean to say is that it is next on my to-do list after my current task.

**Comment by cyclism6486** [comment]
Excellent news - looking forward to it!  Thanks.

**Comment by nowackipawel** [comment]
hi there, thank you for such a fast img browser; could you pls let me know it this feature is implemented in linux version?

**Comment by jurplel** [comment]
Hi! this feature is in the master branch (and is implemented for linux). it will be released with the next qview version.

**Comment by cyclism6486** [comment]
Mac version is eagerly awaited - still using the old daily version linked to a few weeks ago!

**Comment by jurplel** [comment]
yeah, i've been really busy with two internships this summer... I want to work on qView but i just don't have any time nowadays

**Comment by nowackipawel** [comment]
Fingers crossed and thank you! This is only one feature that is missing in such a fast and simple browser/viewer.
