### ISSUE TITLE
HEIC/HEIF support

### ISSUE THREAD

**Issue by njogun** [jurplel/qView#246]
Sorry if this is a duplicate - I searched issues and wasn't able to find any issue about supporting HEIC/HEIF format which is a format (https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) used by newest Apple devices. 

Any plans to support it? 

PS: An open source implementation seems to already exist for the format (https://github.com/strukturag/libheif) - maybe it wouldn't require implementation from scratch.

**Comment by jurplel** [comment]
Good suggestion, I will definitely look into it. I am trying to minimize dependencies as much as possible.

**Comment by ffffwh** [comment]
This app can open HEIC file, but it cannot switch to next/previous HEIC files in the same folder.

**Comment by jurplel** [comment]
You're right, but I don't know why. It will be a fairly simple fix to list it as supported, then.

**Comment by jurplel** [comment]
It appears that Qt on macOS and iOS supports HEIF images by default. The changes on master should allow it to detect this. I will leave this open for now so I remember to check if qt-heif-image-plugin works for other platforms.

**Comment by pphh77** [comment]
[win64: AVIF/HEIC/HEIF support](https://drive.google.com/file/d/1N6wgAX30SohIWjYvaNQ3pP99R6MC_vmU/view?usp=sharing)

**Comment by jurplel** [comment]
> 
> 
> [win32 and win64: AVIF/HEIC/HEIF support](https://drive.google.com/drive/folders/1pAN-5QZ6QMiSAP2V4V_akzhRzhDomW59?usp=sharing)

Can you share how you were able to build qt-heif-image-plugin statically?
