### ISSUE TITLE
Randomized order (shuffle) in folder

### ISSUE THREAD

**Issue by GETandSELECT** [jurplel/qView#247]
Hey

thank you. I in process of switching from Xee (now proprietary software) and would like to see Randomized order (shuffle) for folders.

thank you

**Comment by jurplel** [comment]
Sure thing

**Comment by Hrxn** [comment]
https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

**Comment by brcast** [comment]
diff --git a/src/qvimagecore.cpp b/src/qvimagecore.cpp
index 5ee7add..3da610f 100644
--- a/src/qvimagecore.cpp
+++ b/src/qvimagecore.cpp
@@ -240,7 +240,9 @@ void QVImageCore::updateFolderInfo()
             else
                 return collator.compare(file1.fileName(), file2.fileName()) > 0;
         });
-    }
+    } else if (sortMode == 4)
+        std::random_shuffle(currentFileDetails.folderFileInfoList.begin(),
+                  currentFileDetails.folderFileInfoList.end());
 
     currentFileDetails.loadedIndexInFolder = currentFileDetails.folderFileInfoList.indexOf(currentFileDetails.fileInfo);
 }
diff --git a/src/qvoptionsdialog.ui b/src/qvoptionsdialog.ui
index a118652..f15d5ad 100644
--- a/src/qvoptionsdialog.ui
+++ b/src/qvoptionsdialog.ui
@@ -457,6 +457,11 @@
            <string>Type</string>
           </property>
          </item>
+         <item>
+          <property name="text">
+           <string>Random</string>
+          </property>
+         </item>
         </widget>
        </item>
        <item row="3" column="1">
