### ISSUE TITLE
open multiple files from file dialog

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#25]
Open more windows if you select more files
Also prompt when opening more windows

**Comment by shape55** [comment]
I assume this feature hasn't been added yet?

**Comment by jurplel** [comment]
No, not yet. Since you're asking about it, it'll be a higher priority for me though.

**Comment by shape55** [comment]
Ok, that would be great - thanks :)

**Comment by jurplel** [comment]
resolved in 4d15b97f4a6501f6e715aa4b18d19528f1b11f88
