### ISSUE TITLE
MainWindow with open image is selected when opening from Finder on mac

### ISSUE THREAD

**Issue by epiller** [jurplel/qView#250]
I just upgraded to version 3.0 and I don't seem to be able to open photos in tabs anymore.
In version 2, opening another photo while one was still open would open it up in another tab. Now it seems you need to create a new window and then open the picture.
Would it be possible to have an option between the new mode and the old one?
MacOS 10.15.2

**Comment by jurplel** [comment]
Do you mean, when you open two pictures from Finder, it does not create a new tab/window, but instead replaces the existing one?

**Comment by epiller** [comment]
Yup, exactly that!

**Comment by jurplel** [comment]
This is actually a bug, my apologies

**Comment by epiller** [comment]
It's a free open source program. All the kudos in this world to you for developing and maintaining it. Take your time and cheers!
