### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#252]
I'll probably set up a zanata or weblate or something

**Comment by smarquespt** [comment]
My vote goes for crowdin, it's free for oss. https://crowdin.com/page/open-source-project-setup-request

**Comment by jurplel** [comment]
Good suggestion. For the record zanata has a free for oss thing as well but I'll look at both. I didn't know about that service.

**Comment by jurplel** [comment]
Didn't realize but pretty much everyone seems to have a free plan for open source projects including weblate

**Comment by smarquespt** [comment]
Never used zanata. I've already have accounts at weblate, transifex & crowdin.

**Comment by BloodRaven0** [comment]
You can count me in for the Bulgarian localization :P

**Comment by jurplel** [comment]
I have created a weblate: https://hosted.weblate.org/projects/qview/qview/
It is brand new so if you have any feedback about things that are difficult to translate or systems that don't work, I'd be happy to hear it.

**Comment by smarquespt** [comment]
@jurplel 
The project is there but there are no source strings.

**Comment by jurplel** [comment]
Should be fixed now

**Comment by smarquespt** [comment]
It is. Thanks

**Comment by smarquespt** [comment]
Can you grant me proofreader rights? I don't want magled strings.

**Comment by jurplel** [comment]
I don't know how to do that yet.. what do you mean by mangled strings?

**Comment by smarquespt** [comment]
magled strings are bad translations: https://dictionary.cambridge.org/pt/dicionario/ingles/mangled

In weblate there are many people working in projects, some are good but others are not. For instance, Brazilian people work in Portuguese translation because they think it's the same but it isn't. That's why there is pt and pt-BR but they don't care. So, many projects I've been working on are changed constantly but in a bad way. That's why I've asked you that role. This way I can check if strings are ok and approve them. Others can only make suggestions, not translations.

**Comment by smarquespt** [comment]
I think that this feature isn't available at free plan. But anyway: https://docs.weblate.org/en/latest/index.html

**Comment by jurplel** [comment]
I see, okay. Yeah it does look like that isn't available with the free version.

**Comment by jurplel** [comment]
Do you know if the open source version of transifex has that feature?

**Comment by smarquespt** [comment]
> Do you know if the free version of transifex has that feature?

It does, and crowdin also.

**Comment by smarquespt** [comment]
Typo: https://hosted.weblate.org/translate/qview/qview/pt/?&offset=128, two ampersands

**Comment by jurplel** [comment]
Thanks

**Comment by smarquespt** [comment]
Off-topic: is it possible to print from qview?

**Comment by jurplel** [comment]
At the moment no it is not.

**Comment by smarquespt** [comment]
> At the moment no it is not.

yeah, i didn't find that option but I thought it was my fault.

**Comment by smarquespt** [comment]
https://hosted.weblate.org/translate/qview/qview/pt/?&offset=164

../src/qvoptionsdialog.ui:638

"&Update notifications on startup" -> about new releases

**Comment by jurplel** [comment]
I will add a comment for that clarifying that it is for new releases

**Comment by smarquespt** [comment]
what is the difference form "Quit" and "Exit" in your app?

**Comment by jurplel** [comment]
Exit is for windows

**Comment by jurplel** [comment]
It is the same with settings vs preferences, and About vs About qView
they are operating-system specific variations

**Comment by smarquespt** [comment]
Got it. Thanks, almost done.

**Comment by jurplel** [comment]
I switched it to European Portuguese instead of an ambiguous one

**Comment by jurplel** [comment]
In your opinion, does it make sense for users with Brazillian Portuguese as their default language to default to European Portuguese if Brazillian Portuguese is not available? It has to be better than just defaulting to English, right?

**Comment by smarquespt** [comment]
> Do you know if the free version of transifex has that feature?

crowdin roles: https://support.crowdin.com/modifying-project-participants-roles/
transifex roles: https://docs.transifex.com/teams/understanding-user-roles

**Comment by smarquespt** [comment]
> In your opinion, does it make sense for users with Brazillian Portuguese as their default language to default to European Portuguese if Brazillian Portuguese is not available? It has to be better than just defaulting to English, right?

I really don't know. I don't like having Brazilian strings in pt-PT, but that's just me. If I had to choose i'd rather have english ones

**Comment by Cris--** [comment]
hi, how can i switch the language in the Windows standalone version of qView 4.0? Didn't find anything.

**Comment by jurplel** [comment]
This feature will be available in qView 5.0
