### ISSUE TITLE
Titlebar vibrancy on macOS

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#254]
https://github.com/lukakerr/NSWindowStyles
https://doc.qt.io/qt-5/qmacnativewidget.html#nativeView
Possible options
- Vibrant background titlebar that the image does not automatically occupy
- Vibrant background titlebar that the image does automatically occupy, autohiding
- Transparent titlebar, with or without title
- Maybe even a full vibrant background for the program

I'll see what works

**Comment by chardskarth** [comment]
I'm interested in configuring the title bar (i saw this, just linking for reference: https://github.com/jurplel/qView/issues/30)

How is this configured? Thanks!

Awesome project btw, this image preview feels very lightweight and responsive

**Comment by jurplel** [comment]
Auto-hiding the titlebar ended up being a little bit trickier, so I ended up just hardcoding the present behavior for now. Relevant code is here: https://github.com/jurplel/qView/blob/master/src/qvcocoafunctions.mm

**Comment by chardskarth** [comment]
Hi. Thanks for the reply!

But how do you set that? I'm okay with not auto hiding. I want to open qView with title bar always hidden. 

Thanks! Awesome project!!

**Comment by jurplel** [comment]
Hey, sorry, I did not implement an option for hidden titlebar. It comes with some other complications since I would need to consider how one can move the window and such.

IIRC @jdpurcell's fork has this feature? https://github.com/jdpurcell/qView/

**Comment by vassudanagunta** [comment]
most viewers that do this let you move the window by dragging the photo, which means of course you can't drag to scroll.
