### ISSUE TITLE
Transparent window

### ISSUE THREAD

**Issue by benzsuankularb** [jurplel/qView#258]
Request feature for transparent the window.
I use qView for developing frontend.
So if qView can adjust transparent of the window,
Then I can put qView on top of my working window and compare.

**Comment by ConorGarry** [comment]
I came here to request this very same feature as a mobile developer. 🙏 

The only app I know that hast this is Zeplin which is a heavy cloud-based framework. This would be a very neat feature for qView to have, I could foresee lots of developers adopting qView as a day-to-day utility if this was added.

**Comment by jurplel** [comment]
I believe this is possible in Qt, and it seems like it would help with certain use cases.

Philosophically, I feel like this should be the window manager's job to implement. It should be possible though, for future reference.

**Comment by whitecodes** [comment]
Perhaps implement the window resize with the image zoom first
