### ISSUE TITLE
[macOS] can't launch qView 3.0: developer can't be verified

### ISSUE THREAD

**Issue by AlexanderRevo** [jurplel/qView#260]
Can't run qView 3.0 on macOS Catalina: I get an error telling me that the developer can't be verified.
<img width="532" alt="Screenshot 2020-02-18 at 01 14 07" src="https://user-images.githubusercontent.com/11422776/74693478-4b8ec180-51ec-11ea-9148-623092c30ddb.png">
Affects both the homebrew cask and the .dmg from the website.

**Comment by jurplel** [comment]
This is to be expected unless I pay for the apple developer program and have apple verify the app. You can see similar issues such as the one at https://github.com/hashicorp/terraform/issues/23033 which lists a solution. Sorry for the late response, I have been sick recently.
