### ISSUE TITLE
Unexpected behavior on high DPI displays

### ISSUE THREAD

**Issue by Cellane** [jurplel/qView#261]
I saw in the release notes that qView 3.0 supports high DPI displays, but for me, the behaviour of the 2.0 version was more in line with what I’d expect.

I use MacBook Pro with the retina display (set to the “More space” option in System Preferences, which should correspond to 1680x1050px). If I open the same image (1000x1500px in size) in macOS’ _Quick Look,_ macOS’ _Preview.app_ and _qView,_ followed by pressing `Cmd-0` in Quick Look & Preview.app / `O` in qView to get the original resolution, the result differs.

In both Quick Look and Preview.app, the image is taller than the height of the screen. In qView 3.0, on the other hand, the image is half the size of what Quick Look and Preview.app show and occupies about 75% of the vertical space of the screen. qView 2.0 handled the operation with the same result as Quick Look and Preview.app.

While I understand that perhaps qView’s result is more technically correct, would it be possible to add an option, allowing the user to choose the prefered way of handling high DPI displays?

Thank you kindly and thank you for qView!

**Comment by jurplel** [comment]
Yeah, I can definitely do this.

**Comment by jurplel** [comment]
Fixed in 4ce26e04d3a6ce094a51aab32d3f8f493db7c5b8

**Comment by Cellane** [comment]
Thank you so much! 🎉

**Comment by jurplel** [comment]
If you can give it a test to make sure it works on your end, that would be appreciated: https://dev.azure.com/jurplel/79795e5b-716b-4a59-a698-8605132587c5/_apis/build/builds/726/artifacts?artifactName=qView-nightly-macos.2020-10-27.6&api-version=6.0&%24format=zip

**Comment by Cellane** [comment]
It looks like the behaviour of qView 2.0 was restored successfully! 🎉 That nightly build seems to behave the same as macOS’ _Preview.app_ again.
Thank you so much for your hard work! 🙇‍♂️

**Comment by jurplel** [comment]
You're very welcome! 4.0 should be shipping soon.
