### ISSUE TITLE
Add support for AV1 Image File Format (AVIF)

### ISSUE THREAD

**Issue by novomesk** [jurplel/qView#274]
Hello,
qView can display [AVIF](https://aomediacodec.github.io/av1-avif/) pictures when [my Qt plug-in](http://188.121.162.14/avif/kde.html) with AVIF image support is installed.

Unfortunately .avif and .avifs are not listed among qView supported files.

Following change in mainwindow.cpp solves the problem:

`    QFileDialog *fileDialog = new QFileDialog(this, ui->actionOpen->text(), "", tr("Supported Files (*.avif *.avifs *.bmp *.cur *.gif *.icns *.ico *.jp2 *.jpeg *.jpe *.jpg *.mng *.pbm *.pgm *.png *.ppm *.svg *.svgz *.tif *.tiff *.wbmp *.webp *.xbm *.xpm);;All Files (*)"));`

AVIF testfiles available here:
https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles

Testfiles with animation here:
https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Netflix/avifs

**Comment by jurplel** [comment]
Nice work! I will look into this and see how well I can deploy it and such in the near future. If I were you I would consider opening a git repository somewhere to centralize the project.

**Comment by jurplel** [comment]
It should be working in the latest master, as I have set it to automatically detect what is supported from qimagereader.

**Comment by novomesk** [comment]
There is a fixed string here:
https://github.com/jurplel/qView/blob/dd07afa1c09ec43025e4f2ed646fed3dcf267010/src/mainwindow.cpp#L183
When I want to open first file, I don't see *.avif and *.avifs files yet.

**Comment by jurplel** [comment]
whoops, one second

**Comment by jurplel** [comment]
Sorry, try now

**Comment by jurplel** [comment]
Shortcuts are a little broken on master at the moment. Should be fixed soon.

**Comment by novomesk** [comment]
Those are extra plug-ins from packages called **kde-frameworks/kimageformats**

BTW I started to host my plug-in at: https://github.com/novomesk/qt-avif-image-plugin

**Comment by jurplel** [comment]
Awesome, thank you.

**Comment by novomesk** [comment]
![qView_win_avif](https://user-images.githubusercontent.com/52529860/81199499-03996280-8fc3-11ea-8c62-fe29aa4833ee.png)

I built qView and my qt-avif-image-plugin under [MSYS2](https://www.msys2.org/) on Windows but only as dynamically linked version.

Do you have an idea how to make one big statically linked qView.exe including my plug-in code too?

**Comment by jurplel** [comment]
do you already have qt statically linked to the program without your plugin?
msys2 has pre-built static qt apparently: https://wiki.qt.io/MSYS2

**Comment by jurplel** [comment]
Here, you probably need to add it with `LIBS`
https://stackoverflow.com/questions/20799161/how-to-make-qt-and-qtcreator-link-the-libraries-statically-instead-of-dynamic

**Comment by novomesk** [comment]
Thanks, I will try it later.
Probably I will also need to add Q_IMPORT_PLUGIN macro, to load statically linked plug-in. This is what I understand after reading https://doc.qt.io/qt-5/plugins-howto.html#creating-static-plugins

**Comment by novomesk** [comment]
I had success to make the Windows installer, but I did not make static build. I included necessary DLL files.
My AVIF plug-in is bundled too.
[qview_avif.zip](https://github.com/jurplel/qView/files/4652068/qview_avif.zip)
Security scan:
https://www.virustotal.com/gui/file/56f02241b47ffdedafca95e93c092da5c09696bdc7b6fc96cbe4ce5cab09c5d7/detection
There is a false positive from Qihoo-360 (HEUR/QVM05.1.5540.Malware.Gen)

**Comment by novomesk** [comment]
FYI, the AVIF plug-in was added to [kimageformats](https://invent.kde.org/frameworks/kimageformats) 5.78.0

**Comment by jurplel** [comment]
Really good to know, thanks!
