### ISSUE TITLE
Gentoo & void packages

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#276]
I've no idea how to do gentoo packages so if someone wants to step in this is a good place to be

**Comment by novomesk** [comment]
Take a look at this:
https://github.com/SpiderX/portage-overlay/blob/master/media-gfx/qView/qView-9999.ebuild

**Comment by jurplel** [comment]
Thanks, this will be useful.

**Comment by Justinzobel** [comment]
Distro builds should be the realm of the distro owners. Devs should just provide code and if they desire AppImages/Flatpak/Snaps.

**Comment by jurplel** [comment]
I like your philosophy but at the end of the day, if I don't do it, it probably won't get done. I just want to make my software available to as many people as possible.

**Comment by Justinzobel** [comment]
I made one for Solus and serpent OS so far, if users want software then someone will package it. I'm just eager for 4.0 :D

**Comment by jurplel** [comment]
Someone made a void package so i'll call that close enough

**Comment by novomesk** [comment]
Added to [Gentoo overlay GURU](https://gitweb.gentoo.org/repo/proj/guru.git/tree/media-gfx/qview/qview-4.0.ebuild), see https://repology.org/project/qview/versions

**Comment by jurplel** [comment]
Hey, that's awesome! Thanks for letting me know!
