### ISSUE TITLE
Zooming is always relative (including after original size is used)

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#279]

**Comment by vassudanagunta** [comment]
What does this mean? It's pretty confusing. Does it map to any of the items I have in #460?

**Comment by jurplel** [comment]
This is pretty confusing! Sorry for my awful issue keeping. This is effectively saying "I want to be able to use zooming after I press O for original size without it resetting to 100% first"—part of the oncoming zooming rewrite

**Comment by vassudanagunta** [comment]
Perhaps rename it to "Zooming is always relative"?
