### ISSUE TITLE
Feature request for image switching on scroll wheel

### ISSUE THREAD

**Issue by therealmarv** [jurplel/qView#294]
When using a mouse it would be great to have another general mode for scroll wheels:

1) image change on up and down on horizontal scroll wheel.

2) image zoom in and out on vertical (thumb here on logitech mx) scroll wheel then.

Changing image on scroll wheel up and down would match old Windows ACDsee and also Gwenview supports this image browsing technique.

**Comment by jurplel** [comment]
It will be done.

**Comment by guoweiwei9821** [comment]
> When using a mouse it would be great to have another general mode for scroll wheels:
> 
>     1. image change on up and down on horizontal scroll wheel.
> 
>     2. image zoom in and out on vertical (thumb here on logitech mx) scroll wheel then.
> 
> 
> Changing image on scroll wheel up and down would match old Windows ACDsee and also Gwenview supports this image browsing technique.

agreed!  I want this feature

**Comment by Dex321x** [comment]
What's the status of this? I couldn't find an option to enable scrolling with mousewheel up/down.

**Comment by jurplel** [comment]
Moved to #620
