### ISSUE TITLE
Navigation doesn't work when viewing avif files

### ISSUE THREAD

**Issue by arun54321** [jurplel/qView#301]
I can view avif files without any problems on qview using @novomesk's avif plugin but I cannot browse next avif images which are inside the same folder.

**Comment by jurplel** [comment]
This should be already fixed in the latest nightly builds.
You can find the latest one here: https://dev.azure.com/jurplel/qView/_build/results?buildId=406&view=results

**Comment by arun54321** [comment]
Ok thanks for the fix. I am waiting for github update. I don't understand that azure thingy.

**Comment by jurplel** [comment]
It is gonna be a little while until there is a GitHub update.
You should be able to find links here.
https://dev.azure.com/jurplel/qView/_build/results?buildId=406&view=artifacts&type=publishedArtifacts

If you still can't find them, another way is to join my [Discord server](https://interversehq.com/discord) where a web hook posts every build from the master branch

**Comment by arun54321** [comment]
That Appimage build doesn't even open avif files.

**Comment by jurplel** [comment]
AppImages have their own environment, and currently no image plugins are being added to it. I forgot about that. The easiest way then would be to build qView yourself. I have wrote a brief guide here: https://github.com/jurplel/qView/wiki/Linux-Build-and-Install-Guide

**Comment by arun54321** [comment]
> The easiest way then would be to build qView yourself.

That's not a problem. I already using source compiled build on my machine (ARCH AUR). I'll wait for github sources.

**Comment by jurplel** [comment]
Okay then. There is also a qview-git package.
https://aur.archlinux.org/packages/qview-git/

**Comment by arun54321** [comment]
It works now. I thought I was using git version.

**Comment by jurplel** [comment]
Okay, great!
