### ISSUE TITLE
Show pixels automatically at high zoom levels

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#302]

**Comment by doongjohn** [comment]
I think this is implemented right now.

Also, I think showing pixels when the single image pixel is currently bigger than the single screen pixel would be cool!\
Because I often view pixel art (game assets).

**Comment by vassudanagunta** [comment]
> Also, I think showing pixels when the single image pixel is currently bigger than the single screen pixel would be cool!

I don't it ever makes sense to NOT do this, right?

**Comment by jurplel** [comment]
Duplicate of #356
