### ISSUE TITLE
Remove all unnecessary qimage allocations

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#303]
This should provide a speed increase.

**Comment by sonulohani** [comment]
Could you please explain this issue to me. I will work on this meantime. 

Thanks.

**Comment by jurplel** [comment]
Basically I am referring to the image loading functions in `qvimagecore.cpp` which allocate QImage more often than they need to. This is a part of a restructure of these classes which hasn't been started yet and has been planned for next version.
