### ISSUE TITLE
Incorrect clipboard MIME data

### ISSUE THREAD

**Issue by Myned** [jurplel/qView#307]
`QUrl::fromLocalFile(...)` should be used, which commit https://github.com/jurplel/qView/commit/c0855dd0b80249d82c24338f91b4b9f17217f76a removes and PR https://github.com/jurplel/qView/pull/308 adds back:
https://github.com/jurplel/qView/blob/c0855dd0b80249d82c24338f91b4b9f17217f76a/src/qvgraphicsview.cpp#L308

Without it, the clipboard returns file URLs that do not contain the proper URL scheme. Gwenview, for example, returns the correct URL:

`/home/test/image.png` (master)
`file:///home/test/image.png` (with `fromLocalFile`, same as Gwenview)

This results in some odd behavior depending on the receiving application, such as uploading a copied image increasing the filesize exponentially, and pasting to a directory returning an error about the URL being corrupted. All problems are fixed by adding back `fromLocalFile`.

If the original intention with the commit was to allow network shares to function: according to the [QUrl documentation](https://doc.qt.io/qt-5/qurl.html#fromLocalFile), the `fromLocalFile` member supports remote syntax, and works as intended with a localhost mounted share.

_Tested on Manjaro KDE 5.18.4, Qt 5.14.2 using Klipper_

**Comment by jurplel** [comment]
Cosed via #308
