### ISSUE TITLE
Use macOS rendering engine for image viewing

### ISSUE THREAD

**Issue by sn0wyfall** [jurplel/qView#315]
I'm not really sure how to explain this, but I'll try. On macOS, when imaged are viewed using the native macOS viewing engine, scrolling and zooming are completely smooth at 60 fps. On qview, it seems much more jerky at 20-30 fps (maybe even lower). I believe qview is not using macOS's rendering engine. Is it possible to make it do that?

**Comment by jurplel** [comment]
Are you sure it's framerate related? Gesture support is kinda bad right now and zooming cannot be handled smoothly. Dragging an image should be a good representation of framerate.

**Comment by jurplel** [comment]
I found out what you are talking about and it is caused by pitiful gesture support in qView. See https://github.com/jurplel/qView/issues/170

**Comment by sn0wyfall** [comment]
Thanks! wasn't really sure how to describe it, but I think you're right about the duplicate
