### ISSUE TITLE
Minor version updates

### ISSUE THREAD

**Issue by lorenzofanchi** [jurplel/qView#329]
Dear dev,

Thanks for the great work on qView!
It looks like many things have changed since the release of version 3.0. It would be great to see some of those changes in incremental updates between major version releases, if at all possible.

Thanks for considering!

**Comment by jurplel** [comment]
I have been meaning for a while to make smaller, more frequent releases but I always get a little too ambitious. My development process is changing though as I work on a good CI system and switch to using feature branches rather than polluting master. I will do better on this.

**Comment by lorenzofanchi-enpicom** [comment]
Any chance of an interim release for us M1 folks?

**Comment by lorenzofanchi** [comment]
Any chance of an interim release for us M1 folk?

**Comment by jurplel** [comment]
As soon as I have time~ (I am M1 folk now, as well)

**Comment by jurplel** [comment]
> I have been meaning for a while to make smaller, more frequent releases but I always get a little too ambitious. My development process is changing though as I work on a good CI system and switch to using feature branches rather than polluting master. I will do better on this.

yeah... now plugins slow down releases
