### ISSUE TITLE
Window size and position on multi monitor setup

### ISSUE THREAD

**Issue by TommyShoulders** [jurplel/qView#330]
**Environment:**
- OS: Windows 10
- qView version: 3.0

**Information:**
I have a 3 monitor setup and if I have qView on monitor 2 or 3 and navigate to the next image qView jumps to monitor 1 and the image becomes really small.

I am using the following settings:
Window matches image size: When opening images
Up to: 90% of screen size

If the first setting is disabled it all works as expected, but this is one of the features that made me start to use the viewer so is slightly annoying that it only works on monitor 1.

I've included an image of my monitor setup and what it looks like after navigating to the next file.

![image](https://user-images.githubusercontent.com/12910630/85031690-e2f22a00-b176-11ea-9721-f187e1431f9e.png)

![image](https://user-images.githubusercontent.com/12910630/85032449-c30f3600-b177-11ea-8ca4-059dd7193971.png)

**Comment by jurplel** [comment]
Should be because [this](https://github.com/jurplel/qView/blob/9fb07e0245329b2c67938351337c8643c681d4f5/src/mainwindow.cpp#L391) does not take into account vertical multi-screen setups.
