### ISSUE TITLE
Full screen and then normal is resetting the size of the mainwindow.

### ISSUE THREAD

**Issue by sonulohani** [jurplel/qView#332]
**Environment:**
- OS: Windows 10
- qView version: 3.0 latest master

**Information:**
1. Open qView.exe and maximize it.
2. Open an image
3. Enter Full Screen
4. Exit Full Screen

Expected Behavior: After exiting full screen the qView should be in maximize state
Actual Behavior:  qView is not in maximize state.

**Comment by sonulohani** [comment]
Let me know if you want video description of how to reproduce this bug.

**Comment by jurplel** [comment]
Resolved. Thanks for another great bug report.
