### ISSUE TITLE
F11 Shortcut is not working

### ISSUE THREAD

**Issue by sonulohani** [jurplel/qView#333]
**Environment:**
- OS: Windows 10
- qView version: Current master

**Information:**
1. Open qView.exe.
2. Enable menubar. 
3. Open an image of your choice.
4. Press F11.

Expected Behavior: Should show image in full screen.
Actual Behavior: Nothing happens

**Comment by sonulohani** [comment]
Let me know if you want video description of how to reproduce this bug.

**Comment by jurplel** [comment]
Fixed it--there was an erroneous visibility set that I forgot to delete.
