### ISSUE TITLE
Option to click and move window by clicking and dragging on image

### ISSUE THREAD

**Issue by 67N3XEW316WN** [jurplel/qView#338]
Currently when you click and drag an image it moves the image around within the window. It would be nice to have an option in preferences to enable moving the entire window when clicking and dragging the image. Similar to VLC.

**Comment by jurplel** [comment]
That's a good suggestion. Perhaps holding ctrl/cmd could allow for moving the image around with this enabled.

**Comment by 67N3XEW316WN** [comment]
> That's a good suggestion. Perhaps holding ctrl/cmd could allow for moving the image around with this enabled.

That sounds like a perfect implementation!

**Comment by Justinzobel** [comment]
This is already a feature in some window managers, in Plasma I hold Alt and I can move any window.

**Comment by rlaphoenix** [comment]
I would love it if this feature was implemented. Though personally without the CMD/CTRL requirements and such. I want it to work like MPV, where you can just click and drag.

👍

**Comment by jurplel** [comment]
In case anyone is interested, you can do this on macOS natively using this trick: https://www.mackungfu.org/UsabilityhackClickdraganywhereinmacOSwindowstomovethem

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.

**Comment by Justinzobel** [comment]
Just a quick update on this for others that might be running KDE Plasma, the shortcut is now Meta/Super/Windows Key + Left Click to move any window.

**Comment by jurplel** [comment]
> Just a quick update on this for others that might be running KDE Plasma, the shortcut is now Meta/Super/Windows Key + Left Click to move any window.

<3 kde
