### ISSUE TITLE
Touchscreen gestures rotate the image all over the place

### ISSUE THREAD

**Issue by BloodRaven0** [jurplel/qView#348]
- OS: Windows 10 Pro x64
- qView version: 3.0

I'm not even sure if you tried to implement touchscreen gestures for tablet PCs, but currently, besides from dragging with one finger panning the image as it should, when two or more fingers are involved, the image rotates about 20 times a second, zooms/outzooms like crazy and does all kinds of weird stuff.

Having touchscreen gestures working would be really nice <3

**Comment by jurplel** [comment]
Yeah gestures are super bad right now. Related to #170. Will be solved in the future.

**Comment by jurplel** [comment]
This is resolved with https://github.com/jurplel/qView/commit/34437376886a6fada375b90498d8b3d4d6dc16d6!
It still is probably not perfect but it is __functional__ at least.
