### ISSUE TITLE
The mouse wheel zooms in and out of the picture, but the position will move

### ISSUE THREAD

**Issue by libaineu2004** [jurplel/qView#349]
**Environment:**
- OS: [e.g. macOS 10.15 Catalina, Windows 10, Ubuntu 20.04, Arch Linux]
- qView version: [e.g. 3.0, nightly 2020-05-02.1]
OS:Windows10,x64
qView version:3.0

**Information:**
After I opened a jpg picture, I selected a point A on the pixel on the picture. Use the mouse wheel to zoom in on the picture, the mouse position will deviate from point A at this time. That is, the mouse position will change, it is no longer point A, but point B.
I hope that when the mouse zooms in and out, the image will always follow the current position for zooming.

**Comment by jurplel** [comment]
Can you upload a video?

**Comment by BloodRaven0** [comment]
@jurplel Hey, I also have this issue on Windows 10 x64.
It happens after using middle click to center the image, as seen on the recording below. Afterwards, scrolling with the mouse wheel often resets the position back to the center.
https://user-images.githubusercontent.com/42444745/182455680-beb0718b-4b50-4c5d-bf41-16383277ce65.mp4

**Comment by jdpurcell** [comment]
@BloodRaven0 Do you know if the "Image scaling" setting was unchecked when this happened? If so, I suspect this is related to the "bonus fix" I included in #515.

**Comment by BloodRaven0** [comment]
@jdpurcell The video I posted is with the "Image Scaling" disabled. Enabling it seems to fix the problem... for the most part.
The only time it would re-center is when you were zoomed in, so the image is bigger than the window, then when you pass the 100% mark when the image COULD fit inside the window, it would reset to the center. This happens regardless of the "Image Scaling" option.

**Comment by jurplel** [comment]
That's very smooth, I'd like to see that integrated in some way!

**Comment by libaineu2004** [comment]
This means that the mouse is pointed at A certain pixel in the picture, and the scroll wheel makes the picture zoom in and zoom in, so that the mouse is always at A. And then I zoom in, and then I zoom in, and then I zoom in, and then I zoom in, and then I zoom in, and I'm still at point A.

**Comment by jurplel** [comment]
closing issue since im not clear on its purpose right now
