### ISSUE TITLE
Float on top

### ISSUE THREAD

**Issue by typoman** [jurplel/qView#350]
Very nice and light app and thanks for making this open-source! I thought this could be a nice addition to be able to make the app window always flaot on top. I'm on mac os and don't know how to do it now.
Cheers!

**Comment by jurplel** [comment]
This is a good suggestion for the future.

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.

side note: this should totally be a window manager feature

**Comment by Stolenboot** [comment]
Thank you for the great app!

I really hope that qView can implement this function. Using a window manager is common on Unix/Linux and possible on Windows, but it is not on Mac OS 11. It seems possible on MacOS 12, as BetterTouchTools supports it, but all the window managers I have tried don't support window floating.

I also think that this is not a pure window manager feature. "Stay on top while playing" is a standard option supported by almost all media players. When qView is doing a slide show, it functions like a video player. So supporting floating makes sense to me. Some other viewers I use, like irfanview on Windows and Xee and Phiewer on Mac, have this function built in.
