### ISSUE TITLE
qView 3.0 Compile Fails

### ISSUE THREAD

**Issue by 0pLuS0** [jurplel/qView#351]
**Environment:**
- OS: Slackware 14.2 x86_64
- qView version: 3.0
- qt5-5.9.8_nowebengine

**Information:**
When I compile qView it fails, this is the terminal output;

qView-3.0/src/qvwelcomedialog.ui
/usr/lib64/qt/bin/uic src/mainwindow.ui -o intermediate/ui_mainwindow.h
/usr/lib64/qt/bin/uic src/qvoptionsdialog.ui -o intermediate/ui_qvoptionsdialog.h
/usr/lib64/qt/bin/uic src/qvaboutdialog.ui -o intermediate/ui_qvaboutdialog.h
/usr/lib64/qt/bin/uic src/qvwelcomedialog.ui -o intermediate/ui_qvwelcomedialog.h
/usr/lib64/qt/bin/uic src/qvinfodialog.ui -o intermediate/ui_qvinfodialog.h
/usr/lib64/qt/bin/uic src/qvshortcutdialog.ui -o intermediate/ui_qvshortcutdialog.h
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DVERSION=3.0 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt/mkspecs/linux-g++ -I. -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include/QtNetwork -I/usr/lib64/qt/include/QtGui -I/usr/lib64/qt/include -Iintermediate -Iintermediate -o intermediate/main.o src/main.cpp
In file included from src/mainwindow.h:4:0,
                 from src/main.cpp:1:
src/qvinfodialog.h:17:5: warning: identifier 'nullptr' is a keyword in C++11 [-Wc++0x-compat]
     explicit QVInfoDialog(QWidget *parent = nullptr);
     ^
src/main.cpp:3:30: fatal error: QCommandLineParser: No such file or directory
compilation terminated.
Makefile:315: recipe for target 'intermediate/main.o' failed
make: *** [intermediate/main.o] Error 1

**Comment by jurplel** [comment]
Make sure you're using qt5 to compile qview (I think you might need to use qmake-qt5 on slackware)

**Comment by 0pLuS0** [comment]
Oh what a BONEHEAD I am, I forgot about that... LOL

Been a while since I compiled a QT5 app... HA...

THANKS

**Comment by jurplel** [comment]
No problem at all!
