### ISSUE TITLE
Wrong gamma? (JPEG format)

### ISSUE THREAD

**Issue by Flone-dnb** [jurplel/qView#355]
**Environment:**
- OS: Windows 10 x64.
- qView version: 3.0.

**Information:**
I'm not sure how to name this issue correctly. I'm working with Krita (image editor) and after saving the image to jpeg format the qView shows the image with the wrong gamma. I've used the default Photos app on Windows 10 and it shows the correct colors.
<br>
![qView_bug_1](https://user-images.githubusercontent.com/37961576/93662290-7d188580-fa78-11ea-9c70-21e1a16bbf0b.png)
<br>
The original in Krita:
<br>
![qView_bug_2](https://user-images.githubusercontent.com/37961576/93662301-8c97ce80-fa78-11ea-82bb-44b85b5beb42.png)
<br>
If I export the image from Krita without "Save ICC Profile" option enabled, then the Photos app also shows the line as black.
PNG format seems to not suffer from this issue.

**Comment by jurplel** [comment]
Should be related to #283

**Comment by jurplel** [comment]
closing as a duplicate since it probably is
