### ISSUE TITLE
Zooming in on a high-res picture leaves it blurry

### ISSUE THREAD

**Issue by Squirreljetpack** [jurplel/qView#358]
**Environment:**
- OS: Arch Linux
- qView version: 3

**Information:**
When opening a high-resolution image like this one: [map](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/fae309e2-581e-46ce-93c4-12ecc47a8bfc/de69ph1-8dd10104-5916-4750-bd3a-cdb9e6e3eb4d.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD00OTgzIiwicGF0aCI6IlwvZlwvZmFlMzA5ZTItNTgxZS00NmNlLTkzYzQtMTJlY2M0N2E4YmZjXC9kZTY5cGgxLThkZDEwMTA0LTU5MTYtNDc1MC1iZDNhLWNkYjllNmUzZWI0ZC5qcGciLCJ3aWR0aCI6Ijw9NjYzNyJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.Wy0TAkxXaeWY-frWl4lD87fKpiZt9TNCbPaydqWuVes) Scrolling in leaves the image blurry. This is not due to the image, as its resolution is high.

**Comment by jurplel** [comment]
Any reason why you closed the issue?

**Comment by Squirreljetpack** [comment]
I saw that there was already a high-priority issue on it

**Comment by jurplel** [comment]
Got it, thanks.
