### ISSUE TITLE
Checksum to verify installer

### ISSUE THREAD

**Issue by kleenkanteen** [jurplel/qView#367]
**Environment:**
- OS: Windows 10
- qView version: 4.0

**Information:**
When I first run qview, avast blocks it and says it might be a virus. This is weird since I downloaded image glass before this and that didn't happen. Actually, the first time I installed it it didn't start. A few days later, today, I opened a image using qview and then avast blocked it and put it in a place for a deeper analysis. It's kind of concerning. Would be nice if there was a sha256 checksum listed somewhere one could use to verify the installer file.

**Comment by Hrxn** [comment]
Why use avast at all?

Windows 10 has the Windows Defender built-in.

**Comment by kleenkanteen** [comment]
Quoting [https://www.tomsguide.com/reviews/windows-defender](this), "The downsides are that scheduling scans is too difficult for many to accomplish, there's no protection for web browsers other than Edge or Internet Explorer", which are important parts of a antivirus.
