### ISSUE TITLE
Disable recent files history

### ISSUE THREAD

**Issue by saberblaze** [jurplel/qView#370]
Windows 10 x64
qView 4.0

Would it be possible to add an option in the settings to disable recent files history? I did see there is an option for "save recent files" in the options menu but it must be for something else. I understand we can use the "clear menu" option but an option to completely disable the saving of history would be appreciated.

**Comment by jurplel** [comment]
If you disable save recent files that does actually do exactly what you are describing.

**Comment by saberblaze** [comment]
I have the option "save recent files" unchecked in the options but qView still shows recent files history in the "open recent" menu. If the option is supposed to disable recent file history would it be a bug?

**Comment by jurplel** [comment]
Uh, yes it would.

**Comment by saberblaze** [comment]
Ok, I will look forward to the next the release, thank you.

**Comment by jurplel** [comment]
You're very welcome, thank you for your report!
