### ISSUE TITLE
Wayland segfaults when opening images (likely geometry setting related)

### ISSUE THREAD

**Issue by WhyNotHugo** [jurplel/qView#371]
`qview` crashes for when opening any image (tried jpeg, png and gif). The window opens for an instant (but doesn't render anything except gray) and immediately closes.

[Here](https://gist.github.com/WhyNotHugo/44e0c68e83c1b1b4f99aea20db14c047)'s the output of `strace`. I'm not sure what else might be of use, but happy to provide more debugging details.

On ArchLinux, with Qt 5.15.2.

**Comment by jurplel** [comment]
If this isn't a fresh install, try deleting the configuration file at ~/.config/qView

Do you have anything special about your computer (e.g. arm cpu or something?)

Not sure what could be causing this

**Comment by WhyNotHugo** [comment]
This is a clean install, no config file exists.

I continued doing some testing and found that sometimes images do open. I did a lot more testing and observation, and came onto this pattern:

- `qview` crashes when opening almost any image **if** a config file does not exist.
- Once I'm lucky and some image opened[1], the config file is created.
- `qview` works fine if the config file exists.
- If I delete the config file, it goes back to crashing on most images again.

[1] I've found specific images that work when a config file is absent. One of them is a `png` screenshot taken with firefox, but other `png` screenshots taken with firefox don't show the same behaviour.

### About my setup

I'm on amd64. I'm using `swaywm`, a [tiling](https://en.wikipedia.org/wiki/Tiling_window_manager) compositor. Not sure if that might have any unanticipated behaviour.
I'm on ArchLinux, and the PKGBUILD (descriptor for the package) basically does this:

```sh
cd qView
qmake PREFIX=/usr
make
make INSTALL_ROOT="$pkgdir/" install
```

**Comment by jurplel** [comment]
Does it work with `QT_QPA_PLATFORM=xcb qview`?

**Comment by WhyNotHugo** [comment]
It does, but that's problematic, since it forces `qview` to run under `X11`, which is both more insecure, and does not support scaling, so it renders very blurry. Which is kind of a dealbraker for an image viewer.

**Comment by jurplel** [comment]
Yeah, this is probably the same issue as this one a while back: https://github.com/jurplel/qView/issues/327

**Comment by WhyNotHugo** [comment]
Oh, how did I miss that.

Yeah, my guess is that they may be related. I'm happy to help debug this though.

**Comment by jurplel** [comment]
I think this is fixed now on master--feel free to compile it and confirm
