### ISSUE TITLE
arm binary working

### ISSUE THREAD

**Issue by rforcen** [jurplel/qView#373]
successfully compiled & stripped on armbian 5.9 with **arm64** S905X3 cpu 
`Linux arm-64 5.9.0-arm-64 #20.10 SMP PREEMPT Wed Oct 14 12:04:42 MSK 2020 aarch64 GNU/Linux`

`qview: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=12910b767a1af5fc900fb9bc62e62aa1405fee2d, for GNU/Linux 3.7.0, stripped`

test set passed:
```
********* Start testing of ActionManagerTests *********
Config: Using QtTest library 5.15.1, Qt 5.15.1 (arm64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0)
PASS   : ActionManagerTests::initTestCase()
QDEBUG : ActionManagerTests::testClonedActionsUntracked() 2
PASS   : ActionManagerTests::testClonedActionsUntracked()
PASS   : ActionManagerTests::cleanupTestCase()
Totals: 3 passed, 0 failed, 0 skipped, 0 blacklisted, 390ms
********* Finished testing of ActionManagerTests *********

```

runs pretty smooth

**Comment by jurplel** [comment]
Awesome.
