### ISSUE TITLE
add .xcf support for GIMP 2.10

### ISSUE THREAD

**Issue by gimplyworxs** [jurplel/qView#376]
Can support for GIMP 2.10 files be added?
(It must be possible, as digikam has it, but it's slow to always start such a monster app just to prview a file)

**Comment by jurplel** [comment]
It will work if you install kimageformats

**Comment by gimplyworxs** [comment]
still doesn't work on Linux Mint 19.2 MATE:
Unable to read image data (Error 4)
Maybe kimageformats works on kde systems only ...

**Comment by jurplel** [comment]
That shouldn't make a difference really. What are you using, appimage? Deb? ppa?

**Comment by gimplyworxs** [comment]
The deb package

**Comment by jurplel** [comment]
Where did you install kimageformats from?

**Comment by gimplyworxs** [comment]
from the Mint repos 
it's version 5.44.0
The package name is kimageformat-plugins - is that the correct one?

**Comment by jurplel** [comment]
That is the correct one. I am not completely sure but I believe that version of kimageformats is too old. Try compiling kimageformats from source, maybe.

**Comment by gimplyworxs** [comment]
ok, I'll check that tomorrow.
I'll let you know ...
Thanks for your assistance so far.

**Comment by jurplel** [comment]
For sure, you're welcome.
