### ISSUE TITLE
I think a background transparency feature would be cool

### ISSUE THREAD

**Issue by brian6932** [jurplel/qView#383]
For example adding a transparency slider next to the value slider:
![image](https://user-images.githubusercontent.com/18603393/104876165-1e2f2400-5925-11eb-8d9b-04428600a71c.png)

**Comment by jurplel** [comment]
Right now if I added that, it would just get closer to the base window color (which is white on windows). Adding proper window transparency is a bit tricky.

**Comment by StepanAsk** [comment]
Poor us.
