### ISSUE TITLE
Add lanczos upscale

### ISSUE THREAD

**Issue by askasys-code** [jurplel/qView#385]
Bilinear filtering is good but it would be nice to have also the possibility to have lanczos for better quality.
A list of other upscaling filters like mitchell, box, etc, will be even more appreciated.

**Comment by jurplel** [comment]
I don't think this is possible because I am dependent on Qt.

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.
