### ISSUE TITLE
Big sur icon

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#386]

**Comment by alexdeplov** [comment]
Hi. Thanks for the great app! Love it!
Please take a look at this icon, all you need is just export PNG's: https://www.figma.com/file/UlczoRVPMxWVa7M7OHKHJt/qView-Big-Sur-Icon?node-id=0%3A1

**Comment by jurplel** [comment]
That's great, thank you! I was wondering if it might look better if there were no white borders though--like, just a gray rounded rectangle with the glyph inside.

**Comment by lorenzofanchi-enpicom** [comment]
Looks very nice! @alexdeplov I hope you don't mind, but I took the liberty of adding a new page with the suggestion by @jurplel 

https://www.figma.com/file/UlczoRVPMxWVa7M7OHKHJt/qView-Big-Sur-Icon?node-id=11%3A2

**Comment by lorenzofanchi-enpicom** [comment]
Personally, I like the version **with** the white border :) Looks more interesting
