### ISSUE TITLE
Modal error dialog interrupts image browsing 

### ISSUE THREAD

**Issue by vassudanagunta** [jurplel/qView#387]
**Environment:**
- OS: macOS 11.1 Big Sur
- qView version: 4.0

**Information:**
I have a folder containing images of a variety of formats, including jpg, gif and png, and also a macOS alias to a png image in another directory. When I use the arrow keys to browse through images, I get the following when qView gets to the alias:

<img width="429" alt="Screen Shot 2021-02-01 at 1 48 55 PM" src="https://user-images.githubusercontent.com/2830093/106504562-1b8c0d00-6495-11eb-8018-50f6b08afa40.png">

I can press `OK` and than reverse direction, but cannot continue in the original direction past the alias, much less open it.

It would be more graceful if qView either silently ignored files it could not open or simply displayed the above error message not as a dialog but in the original browse window (as a proxy for the image it could not open) and allow one to take note and proceed with browsing.

**Comment by jurplel** [comment]
Planned actually! https://github.com/jurplel/qView/issues/344

**Comment by cyclism6486** [comment]
My former image viewer (JustLooking) did the silent skip method and I was good with that. But I agree that non-modal would be better.
