### ISSUE TITLE
allow deletion (and silent deletion) of images as they are being browsed

### ISSUE THREAD

**Issue by vassudanagunta** [jurplel/qView#388]
A common use of image viewers is to efficiently sift through a collection of images to cull out the unwanted ones. Most image viewers have a `Delete` command in the file menu and also a keyboard shortcut, often `⌘⌫` to avoid accidental deletions.

I'd recommend `⌫` produces a confirmation dialog and `⌘⌫` deletes silently, with the user of course able to change this behavior in qView's Shortcuts Preferences.

**Comment by jurplel** [comment]
This is a high priority for me, see https://github.com/jurplel/qView/issues/210

**Comment by vassudanagunta** [comment]
ok cool. i'll update the title to help you remember why you're keeping this dupe :)

**Comment by r57zone** [comment]
This would be convenient and would allow you to completely abandon the other viewer programs
