### ISSUE TITLE
Apple Silicon (M1) native build 

### ISSUE THREAD

**Issue by vassudanagunta** [jurplel/qView#389]
Would be nice to have one!

**Comment by jurplel** [comment]
It certainly would. I'll look into it but it might be up to Qt's support.

**Comment by soren121** [comment]
FYI, I have an M1 Mac, and I was able to compile the current git master (9683b2c) using Qt 5.15.2, with no issues at all. Granted, this is an Apple Silicon-only build; I know Qt is still working out how Universal builds will work.

It is _much_ faster than running in Rosetta 2 though. There's a pretty long startup delay of 4-5 seconds when using the 4.0 Intel Mac release, but with a native ASi build, startup is instantaneous.

**Comment by jurplel** [comment]
That's good info, thank you

**Comment by kwanljuin** [comment]
can you share the compiled app for m1?

**Comment by soren121** [comment]
Here's an unofficial, unsupported build of qView for Apple Silicon. It's self-signed so you may need to allow apps from unidentified developers. Use at your own risk, I make no guarantees that it will work and I'm not responsible if it breaks your machine. Please don't bother jurplel about this either.

[qView-arm64-2acc88a.dmg.zip](https://github.com/jurplel/qView/files/6488451/qView-arm64-2acc88a.dmg.zip)

cc: @kwanljuin

**Comment by Morgan1er** [comment]
Hi,
a little UP for this : would really like a M1 version as well :)
Thx

**Comment by jurplel** [comment]
I can't promise I can get all the image format plugins up and running but there will be at least some m1 version released for 5.0. I am considering switching to imagemagick to replace qt image format plugins so i could make automated builds more flexibly.

**Comment by jurplel** [comment]
I believe I have a fully working universal build for 5.0!

**Comment by zx8** [comment]
@jurplel That's great to hear – any ETA on a release? I'm on the edge of my seat! 😁

**Comment by jurplel** [comment]
Most of the binaries are already built—it was actually supposed to be released yesterday but it should be today, now, due to some Qt 5.9 issues that came up when testing the deb builds.
