### ISSUE TITLE
Crash in heif.dll

### ISSUE THREAD

**Issue by novomesk** [jurplel/qView#398]
Open URL... http://188.121.162.14/libheif/oom-4a28c25c8f67b5c19ab742af5296370989f1f5ed.heif
`Unhandled exception at 0x00007FFE19D5046E (heif.dll) in qView.exe: 0xC0000005: Access violation writing location 0x000002292B7C1000.`
![qview-crash](https://user-images.githubusercontent.com/52529860/109480478-db13b500-7a7b-11eb-9320-4c22ec823162.png)

**Comment by jurplel** [comment]
Probably something to do with the downloaded data being sent to QImage::fromData

**Comment by novomesk** [comment]
HEIF file has undefined bit depth but the plugin is not checking that.
