### ISSUE TITLE
Launch speed audit

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#400]
Ensure qView is still opening as fast as possible after the structural changes

**Comment by novomesk** [comment]
I have a suggestion how to increase performance for some formats:

Create no more than one instance of `QImageReader` for each file. I saw that sometimes one instance is used to get only size of the image and the second one is used to get image data.
Calling `.size()` alone can be expensive operation for some formats as it triggers decoding process. If another QImageReader reader is used for the same file, whole decoding process will be repeated.

**Comment by jurplel** [comment]
Thanks for the tip.
