### ISSUE TITLE
Image browsing speed audit

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#402]
I believe the open with code is running too much stuff before the image is displayed in the gui thread. It seems slightly slower to me on a direct comparison.

**Comment by timea-techgirl** [comment]
HEIC format pictures from iphone takes 5 seconds to load on a fast computer. There is a delay of 3 to 4 seconds before showing the next picture pressing the arrow.

**Comment by jurplel** [comment]
Not much i can do about that since I am reliant on the HEIC plugin primarily
