### ISSUE TITLE
Right and Left arrows on the side of the program

### ISSUE THREAD

**Issue by timea-techgirl** [jurplel/qView#406]
It would be great if there were arrow buttons to navigate between pictures with the mouse click.
I have to use keyboard arrows each time now.

**Comment by BloodRaven0** [comment]
I think the beauty of the program is in its simplicity and lack of overlay UI. Though I agree that maybe mouse-based navigation would be useful, I think the arrows ought to be invisible (or have an option to hide them in the settings).

Other options  for mouse navigation include swiping left and right to change images, double-clicking on the edges of the window (or single clicking, like with the invisible arrows) and touchpad gestures for sidesways scrolling (with two or three fingers swipe), which could also be implemented for touchscreen devices.

**Comment by timea-techgirl** [comment]
Yea, options are always useful so that people who dislike a feature can disable them.
I am used to windows photo viewer since the days of windows 7, so I'm used to mouse navigation. I can't do without it.

**Comment by RikuKH3** [comment]
Same here. Using qView on a tablet PC without keyboard is a pain. I suggest making those arrows only appear when you move mouse to the side of the screen (like in "Microsoft Photos" app).

**Comment by jurplel** [comment]
Maybe one day, but this isn't exactly something I had in my original vision for the UI. I do agree that it would be useful to have some sort of mouse based control, though. If it's any consolation, one can use the page back and forward buttons if one has a mouse that has these buttons.

**Comment by jurplel** [comment]
As I am now trying to clean out the issues, and since I don't plan to ever implement this, I will now close the issue. Thank you for your suggestion.

**Comment by jurplel** [comment]
Fair enough, hope you found what you were looking for I guess.
