### ISSUE TITLE
hidden window title bar

### ISSUE THREAD

**Issue by MaxSherry** [jurplel/qView#408]
can you hidden window title bar, only show pictrue.  and drag pictrue to move window anywhere

**Comment by boehs** [comment]
why must people put zero effort into proofreading?

anyway, seems fairly easy to do using `window.setWindowFlags(Qt::Window | Qt::FramelessWindowHint);`

**Comment by jurplel** [comment]
Closing in favor of https://github.com/jurplel/qView/issues/421 as it is more rigorously documented
