### ISSUE TITLE
Reevaluate file association method

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#409]
https://jrsoftware.org/ishelp/index.php?topic=registrysection
Looks like i'm supposed to use HKA instead of HKLM and probably not use HKCR at all, as it seems to display from HKLM and HKCR while only writing to HKCR... yeah registry is confusing.

While you're at it, do local user installation with this:
https://jrsoftware.org/ishelp/index.php?topic=admininstallmode

**Comment by ada101** [comment]
Looks like you could possibly change

https://github.com/jurplel/qView/blob/ff4c7c198cc16524be866234b50a28afbfd15d15/dist/win/qView64.iss#L64-L91

`Root: HKCR; Subkey: ".bmp\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppName}.1"; ValueData: ""; Flags: uninsdeletevalue; Tasks: fileassociation`

to

`Root: HKLM; Subkey: "SOFTWARE\Classes\.bmp\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppName}.1"; ValueData: ""; Flags: uninsdeletevalue; Tasks: fileassociation`

 for example for the line 64
 Line 64 - 91 

and possibly that would be enough?

**Comment by ada101** [comment]
#411 #410
