### ISSUE TITLE
Cannot open files with unicode chars in filename

### ISSUE THREAD

**Issue by m-dp** [jurplel/qView#413]
**Environment:**
- OS: Xubuntu 18.04
- qView version: 4.0-2

**Information:**
I cannot open a fie with qView if the filename contains a non-Ascii 127 char. 
For example, if I rename a file as `è.webp` ,
upon desktop GUI opening qView prompts an alert: 
_Error occurred opening "��.webp": // File not found (Error 1)_
while a console command `qview è.webp` prompts the similar alert: 
_Error occurred opening "??.webp": // File not found (Error 1)_

I find it odd of course to be the first one to note this...

**Comment by jurplel** [comment]
Tested real quick with .png and it works fine. With .webp, it fails. This is probably a Qt or libwebp bug.

**Comment by m-dp** [comment]
Well, thank you jurplel (impressively fast response BTW)! I was now further testing to make sure it was not my system. 
An `LC_ALL=en_US.UTF-8 ; qview è.webp` returns a more fitting, but equally not working, 
_Error occurred opening "è.webp": // File not found (Error 1)_

I will investigate if anything about such bug is known at _libwebp_.

**Comment by jurplel** [comment]
Actually can you test if you can open the webp with a non-unicode name?

**Comment by m-dp** [comment]
Yes, I can confirm that opening an `a.webp` with qView works. 
 
I see that `vwebp è.webp` works. Command `vewbp` is part of the `webp` package, which should use the libraries from the `libwebp-dev` package

**Comment by jurplel** [comment]
Ah okay. On my side I actually found that ALL .webp files do not open. I changed something to fix that in the source code and then `è.webp`worked as well. 

So I just found an unrelated bug on arch linux with qt 5.15.2, libwebp 1.2.0, qview 4.0, kimageformats 5.81, if any of that is important to me later. Definitely worked before...

**Comment by m-dp** [comment]
Good to see that I helped find a parallel bug, even though a serendipity! 
Since you fixed that, if you will at some point have a new build that I can test, I'll gladly do it. 

BTW: further testing, I see that I cannot open a `è.png` with qView: it seems to refuse all filenames with unicode, independently of the extension.

**Comment by jurplel** [comment]
What Qt version? (`qmake --version` should do it)

**Comment by m-dp** [comment]
It's something with Qt: I see that also `è.pdf` for _qpdfview_ and `è.epub` for _ebook-viewer_ (Calibre) do not work. 

> QMake version 3.1
> Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

**Comment by jurplel** [comment]
Try it with qview flatpak maybe

**Comment by m-dp** [comment]
...And today I learned that locale `C` has a brother like regional locales, `C.UTF-8` (I thought it implicit). 
It seems, Qt will fail loading files with unicode names without a right ".UTF-8" in the locale! 
I am not sure which locale environment variable is the critical one for this issue in Qt. I had a LANG of en_US.UTF-8 and a LC_ALL of C - but setting LC_ALL not only fills the various LC_MONETARY, LC_TIME etc.: it also overrides LANG. 

Now all `è.png`, `è.webp`, `è.pdf`, `è.epub` etc. work.

**Comment by m-dp** [comment]
Maybe, if you think it proportionate to the issue, you could update the error message under some further conditions that right now I cannot clearly define (but maybe at error rising stage there may exist a check that suggests an unicode filename): 
_Error occurred opening "???": // File not found (Error 1). // **Is your locale correct?**_

**Comment by jurplel** [comment]
I will strongly consider that and probably do it. good job troubleshooting!
