### ISSUE TITLE
Same window when opening other images

### ISSUE THREAD

**Issue by andreicorpo** [jurplel/qView#414]
Would it be possible to open images in the same window if one already exists?

**Comment by jurplel** [comment]
On macOS?

**Comment by andreicorpo** [comment]
Yes, on macOS.

**Comment by jurplel** [comment]
Presumably from the file explorer, right? That could be added as an option.

**Comment by andreicorpo** [comment]
Actually I'm using qView to open files from the terminal (`open -a qView`) but I think it would replicate the same behaviour as opening from the file manager.

**Comment by jurplel** [comment]
Yeah, it should.

**Comment by dust0vich** [comment]
I would give this a thumbs up for doing this on Windows also, Or a right click menu option to select new or existing window when opening with Explorer.

**Comment by jurplel** [comment]
just closing since it's old

**Comment by Michael-Soyka** [comment]
So, it wasn't implemented?
