### ISSUE TITLE
Image size and position resets unexpectedly when pinching and zooming

### ISSUE THREAD

**Issue by swashbuck** [jurplel/qView#415]
**Environment:**
- OS: BigSur
- qView version: 4.0

**Information:**
Pinch to zoom works great when zooming in and out of an image.  However, once I click to drag the image and then pinch to zoom again, the image size and position are reset.  It seems to reset the image to the center of the window rather than the center of the area that I've zoomed into.  Sometimes, the window goes blank and hides the image altogether, and sometimes the image will flip upside down.  This is a very jarring experience.

I would expect the behavior to work as follows.

1. Pinch to zoom in on the image.
2. Click to drag the image to a different area other than the image's center (ex. the upper right side).
3. Pinch to zoom in again.  This zooms in on the area that's currently in the window's center (ex. the upper right side).

Otherwise, great app.  :)

**Comment by jurplel** [comment]
Hi! The glitchiness with the image turning upside-down and all that should already be fixed in the development build (hopefully a release soon). At the moment, centering is required for the scaling to work, so that improvement will come later on when I rewrite a lot of the scaling stuff. Thanks for reporting!

**Comment by swashbuck** [comment]
Great, looking forward to it!  Thanks for the fast reply.

**Comment by jdpurcell** [comment]
I believe this is fixed now. Probably by #467 and there were some additional quirks fixed in #515 as well.

**Comment by swashbuck** [comment]
Thanks, works much better now!
