### ISSUE TITLE
qView - Usability Review, Praise and Followup!

### ISSUE THREAD

**Issue by porg** [jurplel/qView#416]
# Hi dear developers & designers of qView,

a lot of issues and comments will follow now in the next hours, I already drafted most of them locally, and will commit them now one after the other.

This issue serves as sort of a cover letter to introduce me to the qView community and to you its maintainer @jurplel - hi! - so that you make sense of the flood of issues and comments which will be incoming.

# My compliments to qView

🏆 Since I discovered it qView is now my favorite picture viewer app for presentation purposes on macOS 11 Big Sur!

In the past Apple's native picture/PDF viewer Preview.app pretty much cut it for me.

But since a certain time Preview.app introduced a quite large minimum window size which disqualifies it for certain presentation Purposes.

Presentations such as narrow windows of mockups of mobile apps or websites or multiple smart-watch screenshots/wireframes/mockups side-by-side.

Realistic use cases for folks like UX/UI designers, developers, QA testers, etc. Great that we are covered now! My issues mostly deal with improving these profession's use cases even more.

# Favorite features

🧐 Very true to its slogan: No toolbars or distractions — pure space efficiency
+ Multiple windows to present content side by side
+ No minimum window size (unlike Preview App)
+ Free zooming
+ Clever and customizable zoom factor handling reacting to window resizing
+ With all this together: Very well suited for easy ad-hoc and/or image-collage presentations!

# I want to contribute too

👍 As this is an open source project, it lives from its contribution.
- I cannot contribute in code, but I will contribute in the form of bug reports and feature proposals and some review/recommendations in my social media and personal circles.
- I'm a UX designer by profession since a decade, so my submissions should be of a good enough quality to be clearly comprehensible and implementable.

# Spreading the word

🗣 As your app is really good I'll try to spread the word on it:
- I starred it on GitHub
- I praised qView on Twitter
  - I realized there's neither a [@interverseHQ](https://twitter.com/interverseHQ) nor a "legit" [@qView](https://twitter.com/qview) Twitter account.
  - [@qView](https://twitter.com/qview) only has two tweets from 2019 and nothing more.
    - Maybe you could get it from the owner or maybe even from the platform if it is considered "abandoned", I don't know Twitter's policy on this.
- I will spread the word in my professional design/frontend-development/ circles
- I plan to give you a review on MacUpdate and similar app repositories / marketplaces.

🥂 **Cheers!** 🥂

**Comment by jurplel** [comment]
Hi! Great to meet you, looking forward to your issues and thank you for your high praise. I see a few of them already and the reports are very high quality so thank you for that. At the moment I am in my finals week, so there might be a slight delay in giving these issues the attention they need, but I will try to take a look at them all as soon as possible.

Thanks again!

**Comment by porg** [comment]
Am now done committing my load of bug-reports and feature proposals 🙂 

Came back here and am glad that you already reacted!

I put all issues mostly into explicit writing and they should be self-explanatory. One should be able to pick them up and know, even if no input from me can be provided at that time.

But some parts are maybe not, where it would have been inefficient to put them all in writing or provide detailed wireframes/mockups before even knowing whether you want/can pursue this/that.

So I am offering that we could also have a videocall once, if you'd like.

But should we never get to it, I am glad that I took this entire day to document them as they are, and you can pick up any time later.

So let's see whether we get to it or not.

And all the best for your finals!
