### ISSUE TITLE
Open URL always fails with Error Invalid Image

### ISSUE THREAD

**Issue by porg** [jurplel/qView#417]
- For any supported image type (PNG, SVG, JPG)
- For any website (tried many different ones)
- For any transport scheme (HTTPS and the rare HTTP pages one still finds

# Environment
- OS: macOS 11.2.1 Big Sur
- qView: 4.0, installed via brew

# Reproduction
- File > New Window
- File > Open URL
- Enter URL and press OK
- For pictures large in file size you may shortly see a progress window "Downloading…" but mostly it was instant or only a split second (being on a broadband connection)

# Expected
- I see the image

# Actual
- I get an error window: "Error: Invalid image"
<img width="360" alt="qView Open URL" src="https://user-images.githubusercontent.com/737143/117197713-7280e580-ade8-11eb-9736-d4ed02ecbf70.png"> <img width="360" alt="qView Open URL error" src="https://user-images.githubusercontent.com/737143/117197727-77459980-ade8-11eb-858b-0b6e805738f5.png">

# URLs tried
https://upload.wikimedia.org/wikipedia/commons/e/e9/Hagio_Moto_in_2008.jpg
https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
https://media.giphy.com/media/QpWDP1YMziaQw/source.gif
http://static01.nyt.com/newsgraphics/2021/02/16/oval-office-art/assets/images/top_02-460_x2.jpg
https://static01.nyt.com/newsgraphics/2021/02/16/oval-office-art/assets/images/top_02-460_x2.jpg

**Comment by jurplel** [comment]
I can reproduce. This certainly didn't happen before, so the first thing that comes to mind is to blame Big Sur somehow. On the latest `trash` branch this doesn't happen (but sometimes does???) I'm also getting invalid url on the last 4 URLs. Something might be seriously wrong with my setup here but this bug certainly exists and needs further exploration.

**Comment by porg** [comment]
Any further developments?

**Comment by jurplel** [comment]
Unfortunately no. I have been super busy because I am working two internships this summer, so qview is kind of on the back burner for now :(

**Comment by porg** [comment]
Totally ok! Just wanted to know. As a workaround I will simply download the file into a temporary directory and open locally.
