### ISSUE TITLE
Tabs of preference window have glitched blue separators on macOS 11 Big Sur

### ISSUE THREAD

**Issue by porg** [jurplel/qView#418]
## Environment
- OS: macOS 11.2.1 Big Sur
- qView version: 4.0, installed via brew

## Bug report
- See annotated screenshots below.
- I have not used qView in versions earlier, dunno when the bug occurred or whether it's a regression.
- If this is a new bug, then I suppose it has to do with macOS recents refreshment of general UI controls. Saw similar glitches in other 3rd party apps too, which have not yet been updated for Big Sur.

<img width="360" alt="qView preference window focused" src="https://user-images.githubusercontent.com/737143/117198444-529df180-ade9-11eb-991e-983b3341a13f.png"> <img width="360" alt="qView preference window unfocused" src="https://user-images.githubusercontent.com/737143/117198458-5762a580-ade9-11eb-89fd-a1b3e9dcfae3.png">

**Comment by jurplel** [comment]
Out of my control: https://bugreports.qt.io/browse/QTBUG-86513?jql=text%20~%20%22big%20sur%20tab%22

Should be resolved soon, hopefully backported to qt 5.15.3

**Comment by porg** [comment]
This is a low-priority issue anyhow.
Nice to know that this is a dependency and hence will "solve by itself one day". 😉

**Comment by jurplel** [comment]
Closing cause it's old, and also I don't think I have any control of it anyway. I think it is fixed now?

**Comment by porg** [comment]
Good news: It has "resolved itself" (seemingly from upstream) as of qView 5.0, using Qt 6.2.2, on macOS 11.7.4

**Comment by jurplel** [comment]
Wonderful
