### ISSUE TITLE
Pinch-to-zoom gesture sometimes misinterpreted as rotate gesture on macOS

### ISSUE THREAD

**Issue by porg** [jurplel/qView#420]
## Environment
- OS: macOS 11.2.1 Big Sur
- qView version: 4.0, installed via brew
- I have set "Scrolling zooms" to OFF and "Zoom amount" as 10%.

## Related Issues
- All panning & zooming operations seem to use only very low-resolution input depth ("mousewheel emulation") as already covered in #170 and #266

# Bug
- Sometimes you perform a scroll gesture by two-finger scrolling but unexpectedly this gets interpreted as a rotation gesture.
- And the rotation gesture is extreme — not 1-2 90° rotations but instead more like 10-20 rotations within a split second — see "Related Issues" maybe this very issue is just a side-effect of it.

# Screen recording
- I experience this again and again but did not manage to experience and record the bug.
- But I managed to record all different phases in a controlled fashion in one video:

https://user-images.githubusercontent.com/737143/117200210-7e21db80-adeb-11eb-90bc-abea0db6f904.mp4 

  - Phase 1: Panning (scrolling with two fingers)
  - Phase 2: Zooming (pinch-to-zoom gesture)
  - Phase 3: Rotate with two fingers (flicker-like high frequency rotation)
  - Phase 4: Controlled rotation by up/down arrows

**When I experience the bug** I perform panning (1) and/or zooming (2) but instead experience hi-frequency rotation (3).

**Comment by jurplel** [comment]
If you have the time, try out this version and tell me if the problem is fixed: https://dev.azure.com/jurplel/qView/_build/results?buildId=870&view=artifacts&pathAsName=false&type=publishedArtifacts

This version is post-https://github.com/jurplel/qView/issues/348 and may resolve the issue. It may also have regressions in the trackpad behavior—I do not have a hardware trackpad!

**Comment by porg** [comment]
**Tested qView-nightly.2021-05-05.5 :** 
- No faulty unintended rotations anymore
- Because the rotate gesture is supressed at all.

**Conclusion**:
- I'm proposing this issue as fixed and hope that it's integrated in the next mainstream release.
- But it should be noted that for #170 the final goal should be this:
  - You can rotate by trackpad gesture: The rotation is fully shown, and when the gesture ends, the image snaps at the last nearest multiple of 90°. This is the look & feel of native trackpad rotation in macOS Preview.app

**Comment by jurplel** [comment]
Amazing, thank you!
