### ISSUE TITLE
File sorting also by EXIF date or Creation date

### ISSUE THREAD

**Issue by porg** [jurplel/qView#423]
Would be great if qView could also sort by these other timestamps (where applicable by filetype or filesystem).

## Use case
- You have a photo album. Some photos were kept as-is some got modified.
- With these alternative sorting options you can nevertheless present the album chronologically independent from the editing (=modification date).

## Background Info
- Creation Date as well as Modification Date are supported in all native and most 3rd party Mac apps.
- EXIF dates are present in nearly all digital camera pics and in most cases are more accurate than filesystem dates which on some OSes don't reflect the EXIF date but rather the dates of copying/moving.

## Related
- #94 is there for general EXIF support, but not specifically what of EXIF and how to use it.
- This my ticket would be one application.

**Comment by jurplel** [comment]
Yes, that could definitely be useful. EXIF is kind of a can of worms though.

I am currently using whatever Qt provides: https://doc.qt.io/qt-5/qdir.html#SortFlag-enum with a partially custom natural sorting algorithm.

Looks like Qt does provide birthTime: https://doc.qt.io/qt-5/qfileinfo.html#birthTime that could be used for creation date, but that is for Qt 5.10 and above (could probably ifdef it fairly easily) but not all files will provide birthtime of course, so maybe a fallback to modified would be in order.

Thanks!
