### ISSUE TITLE
On window resize: [ Fit ...  ▾ ] and [ Align ... ▾]

### ISSUE THREAD

**Issue by porg** [jurplel/qView#424]
## Actual

qView as of version 4.0 has the setting "On window resize" with the dropbox-menu [ Fit ...  ▾ ] with the possibilities "Fit whole image", "Fit height" and "Fit width".

## Proposed

We extend this section by another dropdown like this:

> On window resize: [ Fit ...  ▾ ] and [ Align ... ▾]

Depending on the choice in the FIT dropdown the ALIGN dropdown offers specific choices:
- Fit height and align: Left | center | right
- Fit width and align: Top | center | bottom
- Fit whole image and align:  top-left | top-center | top-right | center-left | center-center | center-right | bottom-left | bottom-center | bottom-right

## Design Rationale

<img width="962" alt="qView Fit 1" src="https://user-images.githubusercontent.com/737143/117216805-9b14d980-ae00-11eb-9df4-7621ecb6873b.png">
<img width="962" alt="qView Fit 2" src="https://user-images.githubusercontent.com/737143/117216992-f777f900-ae00-11eb-8953-fb0ce4ca946f.png">
<img width="962" alt="qView Fit and Align 1" src="https://user-images.githubusercontent.com/737143/117216811-9e0fca00-ae00-11eb-9f5e-6d2dc2c57541.png">
<img width="962" alt="qView Fit and Align 2" src="https://user-images.githubusercontent.com/737143/117216812-9ea86080-ae00-11eb-9a86-b788a844cead.png">

**Comment by jurplel** [comment]
Good suggestion!

**Comment by porg** [comment]
Status?

**Comment by vassudanagunta** [comment]
If we have the core controls described in #460, I don't think the above will be necessary because you can get pretty much everything with those:

- browse images with stable top edge: set Window size to `auto`. Window resizes to image size, so no centering takes place (it's not applicable). 
- browse images so they stay centered in window: set Window size to `fixed`. If the image is smaller than the window size it will be centered (that's what all the image viewers i've used do).

**Comment by porg** [comment]
1. First of all #460 is a great issue covering the topic of window and view control on a holistic level.
2. I will therefore close this issue, and integrate my proposal there.
3. Yes my proposal needs integration into your concept, as your proposed controls would not cover my use case.

## My use case

![qView - Scenario window fixed and image series with same width but varying height](https://user-images.githubusercontent.com/737143/171730481-62b8cc45-d07d-41a1-b93c-3a9b201761f7.png)

- For presentation purposes I use a set of windows which shall occupy a fixed size and position on my screen.
  - Hence I set `View` > `Window Size` to `☑️ Fixed `.
  - Note: Setting `View` > `Window Size` to `☑️ Auto` is unacceptable in the scenario, because for stable presentation purposes I do not want the window to auto-resize the height, but occupy a fixed space at a fixed position.
- The width of the image series always matches their parent window
  - Either at 100% zoom, because content and window have the same amount of physical pixels
  - Or because `View` > `Image Fitting` >  `☑️ Shrink to fit horizontally` and `☑️ Stretch to fit horizontally` are both on.
- So our `View` menu will need to be reworked a bit further to support use cases like this one.
- Closing this now. Work will be continued in #460
