### ISSUE TITLE
"Rename" operation general improvements and macOS compliance

### ISSUE THREAD

**Issue by porg** [jurplel/qView#425]
# All OS

## Rename dialog: The initial text selection should be the filename without the dot and fileextension
<img width="720" alt="qView renaming dialog initial text selection" src="https://user-images.githubusercontent.com/737143/117220961-9f44f500-ae08-11eb-93f2-6861f7ec4005.png">

As a general UX recommendation regarding renaming this is the most efficient selection for renaming:
- Just type to overwrite entirely.
- Arrow-right then type to add to the end.
- Arrow-left then type to add to the beginning.
- Overwriting the suffix is the exception. It's still possible, but takes some more keystrokes. Appropriate for rarer use cases.

# macOS

## Default shortcut for "Rename…" currently is F2
- F-keys at all and their standardization reflects 1987 [IBM Common User Access](https://en.wikipedia.org/wiki/IBM_Common_User_Access) still conventional on Windows and many Linux distros.
- But the Mac never made use of them, instead used more mnemonic alphabetical key-bindings as CMD-S for "Save" etc.
- In Finder renaming is bound to ENTER. Was once CMD-Enter. Still commonplace in some 3rd party apps.
- I recommend CMD-ENTER, as renaming is not the main use case in an image viewer, preserving ENTER for more frequently used functions such as toggling fullscreen or entering an edit mode (as in Apple Photos) and SPACE for play/pause (currently "P" in qView, that's ok)

## Implement the default macOS window bar renaming dialog
as an additional macOS standard compliant means for renaming, see screenshot:
<img width="863" alt="qView renaming dialog as all native apps" src="https://user-images.githubusercontent.com/737143/117220982-a835c680-ae08-11eb-9bba-79380ce8ac01.png">

**Comment by jurplel** [comment]
Excellent suggestions. Will definitely change the rename dialog default selection. Will also definitely switch to ⌘ Enter as the default mac rename bind, although enter is not currently used.

The third suggestion would be nice but is probably not worth the work and upkeep it would take. It is at moments like this where one wishes qView was a mac-native application.

Thanks again.

**Comment by porg** [comment]
2 out of 3 to be done… What more do we want for Mac UX happiness!

Mac perfection (3 out of 3) was anyhow only a thing in the Steve Jobs days 😉

**Comment by porg** [comment]
**Reopening**:
- After having tested `qView-nightly.2021-05-19.1`
- Reopen this very ticket or #427, however you prefer organisationally.
- Anyway my report here where it topically originated from:

**Quality Assurance:**
- ✅ 1) CMD-R brings up the rename dialog.
- ✅ 2) Dialog correctly preselects "Screen 1" (including the space character) and not ".png".
- ❌ 3) But quite many edge cases fail:
  - a) "Screen 1.low.png" selects the whole string. --> In case of multiple extensions I propose to select everything until before the last ".extension".
  - b) From then on the routine seems to be confused, and always selects everything, also if you have renamed to "Screen 1.png"
- ❌  4) The the menu bar "F2" is shown next to "Rename…" instead of "⌘-R".
-❓ 5) What about the name bind ⌘-ENTER which was planned? I mean R for Rename is a good mnemonic, but could get in conflict with i.e. a "Rotate…" (by degree iinput) dialog (should that come one day).

**Comment by jurplel** [comment]
4) I will fix that
5) F2, ⌘R, and ⌘Enter are bound to "Rename...", Qt is showing the first one only.
6) ⌘Enter is bound, but I left ⌘R as a default for now as it has been one in earlier versions and I have no reason to remove it for now.

Make sure to reset your keybinds to default in the settings.

**Comment by porg** [comment]
5. Great that you will try to show the main "to be learned" keystroke of the multiple available keybinds in the menu. F-keys were never ever part of the macOS Human Interface Guidelines, at most as some very very low-citizen or arbitrary keybindings such as custom-text-styles in Desktop publishing or Command Line backwards compatible software.

Please post here when the new build which shall fix 4-6 is available for testing. Will test again then.

**Comment by jurplel** [comment]
I actually can't reproduce 4—it doesn't make sense in the code for it to do this either so I can't explain it. 5 was fixed though. When I fix my builds i will post here (hopefully i don't forget).

**Comment by porg** [comment]
I do not know what of the filename is passed on to qView
But on the Mac maybe the file specific flag "hide/show file extension" makes a difference?

And yes, just pint me when the fix is built, I can try then.

**Comment by jurplel** [comment]
https://dev.azure.com/jurplel/qView/_build/results?buildId=1011&view=artifacts&pathAsName=false&type=publishedArtifacts (use macOS)

**Comment by jurplel** [comment]
I am planning to draft a release in the next couple of days. I have tested it repeatedly and it seems to be working, with both file extension visibility options as well. Let me know if you test it out and find anything.

**Comment by porg** [comment]
Short notice to you: No time to test simply for the purpose of testing. But when the next occasion comes, I will report back positively if I recall hopefully, or will report more certainly if things should not work out.

**Comment by jurplel** [comment]
Thank you!
