### ISSUE TITLE
Expression is always false because 

### ISSUE THREAD

**Issue by ZanyXDev** [jurplel/qView#430]
https://github.com/jurplel/qView/blob/e2bfcf7a7b643497845b078c5ae13f3d49a94e7c/src/actionmanager.cpp#L547
because 'else if' condition matches previous condition at line 
https://github.com/jurplel/qView/blob/e2bfcf7a7b643497845b078c5ae13f3d49a94e7c/src/actionmanager.cpp#L539

**Comment by jurplel** [comment]
Thank you for these!
