### ISSUE TITLE
copy current image to the clipboard

### ISSUE THREAD

**Issue by bart9h** [jurplel/qView#431]
It would be nice to be able to copy the current image to the system clipboard.

Either by Ctrl-C or the context menu.

**Comment by jurplel** [comment]
Is this feature not already implemented?
![image](https://user-images.githubusercontent.com/10716694/121780721-9b2a9680-cb6f-11eb-84b3-ce0e777f18f0.png)

**Comment by bart9h** [comment]
sorry, I don't know how I missed it :)

**Comment by jurplel** [comment]
No problem, have a great day!
