### ISSUE TITLE
qView has a Wayland generic icon in its title bar and in alt+tab menu when running on Wayland session of KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [jurplel/qView#432]
**Environment:**
- OS:  Arch Linux
- qView version: qview 4.0
- 
**Information:**

Steps to reproduce:
1. use a linux distribution with KDE Plasma desktop environment
2. log in to Wayland session of KDE Plasma desktop environment
3. install qView
4. open qView
5. observe the Wayland generic icon in the upper left corner of qView window. Also press alt+tab and hold alt key and you will see the same Wayland generuc icon.

Maybe the following link can help you to solve this issue.

https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

![qview](https://user-images.githubusercontent.com/15967631/122672900-422cb500-d1a4-11eb-8868-6355e361d573.png)

**Comment by jurplel** [comment]
Thanks for the report. 

Note for me: Based on that page, it is possible that this is caused by not adhering to the domain spec (which is already fixed).
