### ISSUE TITLE
Wrong image scaling on 4K display

### ISSUE THREAD

**Issue by elman22** [jurplel/qView#436]
**Environment:**
- OS: Manjaro Linux
- qView version: 4.0

**Information:**
When I open an image on 4k display with scaling 200 %, image is shown at 200 %. Imagine you have picture with 100x100 px. When I open it on 4K display, I still expect it to be shown at 100x100 px and not scaled to 200x200 px. Only GUI should be scaled at 200 %.

**Comment by jurplel** [comment]
Probably related to this: https://github.com/jurplel/qView/issues/374

**Comment by jurplel** [comment]
closing in favor of #374
