### ISSUE TITLE
Windowless Mode for MacOS

### ISSUE THREAD

**Issue by AnirvanB** [jurplel/qView#437]
An option in preferences to enable windowless mode for MacOS. For reference, links to some of the image browsers that incorporate the said feature:

https://lilyviewapp.com/#
https://www.imagetasks.com/pixea/

**Comment by jurplel** [comment]
good idea! thought about doing something autohide-y at one point.

**Comment by AnirvanB** [comment]
Thanks for considering @jurplel. Any chance this can be a part of milestone 5.0.

**Comment by jurplel** [comment]
I think that is a bit too ambitious--I am trying to keep milestone scope down as much as possible and it still ends up too big nearly every time.

**Comment by jurplel** [comment]
I still say this would be cool, but I think this realistically won't happen so I'll close the issue for now.
