### ISSUE TITLE
Exit the app when the window is closed

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [jurplel/qView#438]
On mac, after closing the window, the software will stay in the background, every time I use command+q to quit actively makes me feel a little annoyed, can you add the option to quit after closing the window?

Thanks.

**Comment by jurplel** [comment]
Hi--I am actually following the standard for macOS apps as I know them (some interesting background in this stackoverflow post: https://ux.stackexchange.com/questions/120762/on-macos-why-does-closing-windows-not-quit-the-app). 

I don't think this is something that many people need but if there is significant demand then I can consider adding it. Thanks for your feedback.

**Comment by fharper** [comment]
I was looking for the same. I agree with following the standard, but what I've seen in most applications is an option to activate this, so by default it's how macOS apps works, but for the people who wants that, they can enable it. What do you think @jurplel ?

**Comment by jurplel** [comment]
Sure thing
