### ISSUE TITLE
Unable to rename files on Windows

### ISSUE THREAD

**Issue by climbTheStairs** [jurplel/qView#439]
**Environment:**
- OS: Windows 10
- qView version: 4.0

**Information:**
When an image is open in qView, I cannot rename it, whether using the native rename feature (F2), or with any other application, because it is being used by the qView process.

Attempting to rename with qView gives the following error:

```
Error: Could not rename file
(Check that you have write access)
```

**Comment by jurplel** [comment]
How did i not find this earlier?!?!
