### ISSUE TITLE
Add keyboard shortcut for Random image and/or add Sorting to context menu

### ISSUE THREAD

**Issue by calico-cat968** [jurplel/qView#440]
qView now has the new _randomized sort order_, which I absolutely love, but every time I want to use it, I have to go to **Preferences** > switch to **Miscellaneous** tab > select the option from the **Sort files by** drop-down > **OK**. And repeat that to switch back to the previous one or choose a different type, which I do quite often...

I think it'd then be nice to have a keyboard shortcut to jump to a random image in the folder (R for example) or have the **Sort files by** option in the context menu (similar to **View** and **Tools**, perhaps).

Thanks for the awesome software!

**Comment by jurplel** [comment]
Nostalgia for https://github.com/jurplel/qView/issues/67

**Comment by calico-cat968** [comment]
What about the **Sort files by** option in the context menu? Is it hard to implement?

**Comment by jurplel** [comment]
It would be unprecedented in this program but probably not that difficult. I just have a lot of bigger priorities and little available time.

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.
