### ISSUE TITLE
“qView” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by LeNewcomer** [jurplel/qView#445]
**Environment:**
- OS: Big Sur Mac mini M1
**Information:**
I downloaded qView, but upon launch I get this message

 **“qView” cannot be opened because the developer cannot be verified.
 MacOS cannon verify that this app is free from malware." 

 Move to Trash (or) Cancel."_**

How do I open the bloody app????

**Comment by jurplel** [comment]
https://support.apple.com/en-us/HT202491

Without paying the $99/year apple developer fee, there is nothing I can do about this.

**Comment by Hrxn** [comment]
Apple's stupidity tax..

**Comment by jurplel** [comment]
😔
