### ISSUE TITLE
Please add horizontal mouse wheel support

### ISSUE THREAD

**Issue by RikuKH3** [jurplel/qView#446]
My Microsoft Mobile Mouse 3600 have ability to press wheel left and right (horizontal scroll) and I would really appreciate ability to switch between photos using this feature.

**Comment by kleenkanteen** [comment]
Just use the arrow keys bruh no one has a horizontal mouse wheel

**Comment by vassudanagunta** [comment]
> no one has a horizontal mouse wheel

actually most people have trackpads and those have "horizontal mouse wheel" behavior, *"bruh"*.

**Comment by kleenkanteen** [comment]
> You have [a habit of dissing other people's suggestions](https://github.com/jurplel/qView/issues/459#issuecomment-987829856). You probably need to kleen your kanteen 🤣. 
Just because you are offended doesn't mean I have a habit of anything 🤣

**Comment by jurplel** [comment]
I have a horizontal mouse wheel :p

qView actually has explicit support for horizontal mouse wheels if you turn off zooming on scrolling / hold cmd/ctrl.

Never thought to make it change images though. Maybe one day, this is an interesting idea. I think post 6.0 though.

**Comment by vassudanagunta** [comment]
@jurplel Could qView be hardcoded to show a Code of Conduct image every nth image for very specific users? 😉

**Comment by kleenkanteen** [comment]
Smells like someone needs to change their diaper 😉

**Comment by jurplel** [comment]
I think that I will close this issue for now since I don't see myself getting to it anytime soon. Feel free to reopen
