### ISSUE TITLE
SVG "Unsupported image format"

### ISSUE THREAD

**Issue by Paulemeister** [jurplel/qView#448]
**Environment:**
- OS: [ Arch Linux]
- qView version: [4.0]

**Information:**
Opening svg files results in "Unsupported image format (Error 3)" even though it is officially [supported](https://interversehq.com/qview/formats/).
jpgs open just fine.
I am pretty new to arch (just trying it out in a virtual machine), so it's possible I made an error somewhere. I installed qView through yay (https://aur.archlinux.org/qview.git).
I am using xfce as my desktop environment, if that is useful. Thanks in advance.

**Comment by jurplel** [comment]
You need this probably: https://archlinux.org/packages/extra/x86_64/qt5-svg/

**Comment by Paulemeister** [comment]
Thanks. The website should be updated to show that.
