### ISSUE TITLE
JFIF not listed as supported

### ISSUE THREAD

**Issue by KaleidonKep99** [jurplel/qView#451]
**Environment:**
- OS: Windows 11 (22000.194)
- qView version: 4.0

**Information:**
JFIF doesn't seem to be in the list of supported formats, yet the files can be opened just fine.

![image](https://user-images.githubusercontent.com/11065274/134283452-6c9ce4c7-fd22-4d82-9ec8-d712a181714e.png)

**Comment by jurplel** [comment]
I have never heard of a JFIF before so that would be why (also it's not on Qt's support list). Should be tested more.

**Comment by Hrxn** [comment]
JFIF is basically JPEG...

A slightly different container, so to speak, only relevant for some metadata. But they are compatible, that is all that matters.
