### ISSUE TITLE
dont know if this is a bug or im dumb

### ISSUE THREAD

**Issue by bladeesucks** [jurplel/qView#454]
ive installed qview (windows) and it "doesnt work".
![image](https://user-images.githubusercontent.com/85462214/137133270-2f62e033-fcec-41ae-aeed-8b79e71beac6.png)
![image](https://user-images.githubusercontent.com/85462214/137133336-98e37e01-e4f7-45d7-97e4-c72fda46c2d3.png)
title bar dont change.

**Comment by jurplel** [comment]
Change it from basic—that's what basic does.

**Comment by bladeesucks** [comment]
changed to minimal and the windows title bar still here, it just shows the file name now.
![image](https://user-images.githubusercontent.com/85462214/137230701-06338841-75cb-48a4-b8c1-003477f400d5.png)

**Comment by jurplel** [comment]
No problem, good luck!
