### ISSUE TITLE
Taking Screenshots - Images Viewed Are Blurry

### ISSUE THREAD

**Issue by 0pLuS0** [jurplel/qView#456]
**Environment:**
- Slackware 14.2
- qView version: 4.0
24" Monitor 1920x1080

**Information:**
I'm not sure why this is, but when I take a screen shot using;

bash -c "import /home/foo/ScreenShots/screenshot-$(date +%m-%d-%Y).png"

When I click on these png files, they are always blurry.

What is odd, if I download a image of similar size, 1920x1080 and view it in qView they are clear. All images I look at in qView are always clear, only screen shots taken are blurry.

How can I correct this?

THANKS

**Comment by 0pLuS0** [comment]
Hi @jurplel any thoughts here?

I do a lot of screen shots for various things, and need a viewer, but this is making the work difficult, ending up with blurry screen shots.

So I don't know if this is an issue using 'bach -c import' or with qView, any feedback would be greatly appreciated.

Thanks

**Comment by jurplel** [comment]
I really can't think of what it could be... can you send me an image maybe?

**Comment by 0pLuS0** [comment]
Hopefully you have Feh, so you can compare them side by side, and see if you notice any differnence as well.

Thanks


![qView_test](https://user-images.githubusercontent.com/36190223/142083342-568611dd-b8e8-4550-81dd-aca997b1e035.png)

**Comment by jurplel** [comment]
I think it's caused by this: https://github.com/jurplel/qView/issues/259

**Comment by 0pLuS0** [comment]
So need to wait on a patched version, or the next release?

Thanks

**Comment by jurplel** [comment]
No there needs to be a rewrite of an import bit of code. I will try to do it sooner rather than later but I have been busy starting at a new university with co-curriculars so qView has been lacking updates for a bit.

**Comment by 0pLuS0** [comment]
Ahh yes, Life... LOL

Well I hope you'll have time soon I could really use this change(s).

THANKS

**Comment by 0pLuS0** [comment]
@jurplel Hi, did you just Commit this today?

Because I just did git clone https://github.com/jurplel/qView.git and compiled it, and still see the same issue... hmm

**Comment by jurplel** [comment]
I did commit it today—I thought this was the same issue as #259. I compared feh and qview and it looks the same to me. Can you elaborate on how to maybe reproduce this?

**Comment by 0pLuS0** [comment]
There is nothing more to elaborate on, I explained exactly the problem in the original post, that is all there is to it. 

Sorry there isn't more to say, but there isn't.

**Comment by jurplel** [comment]
Ok, does it look the same if you use original size? It might be that feh is just not scaling it, that seems like the default to me.

**Comment by 0pLuS0** [comment]
Ahh interesting, no matter what size I view a screen shot, all sizes are blurry.

Not sure if any of this helps, but I got this back at the term when running qview;

 ~ >qview 
libpng error: Read Error
"QImageReader::size gave an invalid size for screenshot-01-06-2022.png, using size from loaded pixmap"
libpng warning: iCCP: known incorrect sRGB profile

**Comment by jurplel** [comment]
I don't think those messages would have anything to do with this, they just kinda show up and are fairly inconsequential. I really can't think of what this issue might be...

**Comment by 0pLuS0** [comment]
I also tried with the Filtering and Scaling options off, nothing worked...

**Comment by jurplel** [comment]
Just to double check, I meant the original size feature accessed by pressing "O"

**Comment by 0pLuS0** [comment]
AHHH pressing the o key works, but that's it, so I'm locked into only having one choice/option. hmm

If I use the Mouse Wheel and try to scroll the size up and down, which I like this ability to do so, being able to look at it, at various sizes, with the mouse wheel, no size is clear.

So anyway to make this work using the mouse wheel?

Thanks

**Comment by 0pLuS0** [comment]
Also is there any fix for this  libpng error: Read Error?

libpng warning: iCCP: known incorrect sRGB profile

Thanks

**Comment by jurplel** [comment]
Well it looks clear because it is being displayed pixel perfect. From what I can see feh looks the same if they are both scaled down.

The libpng error is out of my hands, I don't think there is any fix.

**Comment by 0pLuS0** [comment]
One last thing, I have to double click on all the images that I display in Full Screen, max size to get rid of the title bar, otherwise the title bar appears at the top of the screen shot, cutting out the top view, is there a way to have the title bar permanently disabled when viewing images?

Thanks

**Comment by 0pLuS0** [comment]
Also I've had these libpng errors in the past, my understanding is it has to do with the format of the images you included causing this, nothing to do on my end.

Have a look at this;

https://wiki.archlinux.org/title/Libpng_errors

**Comment by 0pLuS0** [comment]
Also I've had these libpng errors in the past, my understanding is it has to do with the format of the images you included causing this, nothing to do on my end.

Have a look at this;

https://wiki.archlinux.org/title/Libpng_errors

**Comment by jurplel** [comment]
> One last thing, I have to double click on all the images that I display in Full Screen, max size to get rid of the title bar, otherwise the title bar appears at the top of the screen shot, cutting out the top view, is there a way to have the title bar permanently disabled when viewing images?
> 
> Thanks

This would be best done through your window manager

> Also I've had these libpng errors in the past, my understanding is it has to do with the format of the images you included > causing this, nothing to do on my end.

> Have a look at this;

> https://wiki.archlinux.org/title/Libpng_errors

There are no included images, though? Doesn't the error appear when one loads an image?

**Comment by 0pLuS0** [comment]
The last time I had these issues, it was always with the images that were compiled into the app, like Menu Icons, etc... I had to run imagemagick convert on the images in an applications source, then compile it and I never had the issues.

 convert -strip input_filename output_filename

Where are the images coming from in the qview menu, in this screen shot?

![qview_menu](https://user-images.githubusercontent.com/36190223/148473285-eef78f71-b1ae-4607-a0ae-ee940aa9a73e.jpg)

**Comment by jurplel** [comment]
They are gathered from the desktop environment. there is actually only one image baked in that i forgot about—the checkmark for the welcome dialog. sure enough that could be causing it.

**Comment by 0pLuS0** [comment]
I use LXAppearance, and I just changed my System Icons, and the Menu of qview did not change. These menu icons have to be from you.

**Comment by jurplel** [comment]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/10716694/148473846-9fd45abc-f1ac-44f2-b690-80d41e20f3f7.png">
maybe you had to restart qview? not sure why that would be but changing system icons does change the icons for me.

**Comment by 0pLuS0** [comment]
I aplogize, LOL, I forgot this is a QT app... hehe...

Ok I used QT5 Config and changed the icons, but with a different icon set I still get this issue.

So here's all I can tell you, I'm not a coder, but I've been geeking it in Slackware 20 years, if there was this issue wide spread, then I'd see it from every application I am using, afterall these are my icons I am using, therefore the issue would not simply appear in one application and not appear in another when it's an libpng.

Make sense?

qview is some how throwing this error on any icon set I'm testing it on.

I also just tested this on Also I've had these libpng errors in the past, my understanding is it has to do with the format of the images you included causing this, nothing to do on my end.

I also just tested this on Adwaita icons, which come from Slackware;

adwaita-icon-theme-3.18.0-noarch-1

The adwaita icon Slackware package does not have any libpng incorrect sRGB profiles.

This is an issue being throw from qview.

**Comment by 0pLuS0** [comment]
Sorry for this extra reply, I just edited over my last comments, so be sure to look back. 

THANKS

**Comment by 0pLuS0** [comment]
Sorry for these extra replies, I just want to make it clear, that if I open an image and press o it is not clear, it is blurry.

So I either have to double click in the qview window, or set a Fullscreen key and use that and make qview go into full screen mode, then press o and the image is clear.

hmm

THANKS

**Comment by jurplel** [comment]
> Sorry for these extra replies, I just want to make it clear, that if I open an image and press o it is not clear, it is blurry.
> 
> So I either have to double click in the qview window, to make it go full screen, or set a Fullscreen key and use that and make qview go into full screen mode, then press o and the image is clear.
> 
> hmm
> 
> THANKS

Wow, that makes no sense! Any chance it  could be your window manager somehow? Really weird.

**Comment by 0pLuS0** [comment]
I've run into this issue in the past, it's not something new to me.

The problem back when I first ran into it, were the images inculded with an app. So I converted them in the source and then when I recompiled the app and ran it, all fixed.

As I mentioned, if it was something on my end, the issue would appear in any application that has images they included, that are compiled into the app, which are typically the Logo of an app, and all the various menu icons.

I don't see this error in any application I use, that is why it's not on my end, it's not an error that is specific to any particular set of icons/images, that would generate itself this way only for one application.

None of my icons/images have any incorrect sRGB profiles, if they did, as I mentioned, this error message will appear in any application I use, that uses the icons/images.

**Comment by 0pLuS0** [comment]
Oh, as far as, needing to view first in full screen, then press o and the image is clear, I have no idea.

But it could be possible, as I'm noticing using other image viewer apps, that screen shots also appear blurry in them.

What the fix is, I have no idea, as to why this is happening, other then the version if imagemagick that is in Slackware has this bug, when running this cmd is causing it;

bash -c "import /home/foo/ScreenShots/screenshot-$(date +%m-%d-%Y).png"

Slackware 14.2 uses imagemagick-6.9.4_9 I'll have to look into upgrading to a new version and see if it corrects this blurry screen shot issue.

THANKS

**Comment by jurplel** [comment]
No problem. For some reason I am randomly unable to reproduce the PNG ICC profile error, but I went ahead and changed the image to a stripped version anyway, hopefully that solves the error message.

I hope I was able to help in some way or another!

**Comment by 0pLuS0** [comment]
I'm looking to grab the latest version of imagemagick and compile and install it, I'll let you know if that improves the blurry screen shots, thanks a lot for your time help. :)

**Comment by 0pLuS0** [comment]
I compiled and installed imagemagick-7.1.0_19.

I then ran;

```import -window root test.png```

It's the same, so I don't know why this is, unless Openbox I am using has anything do to with it.

I have qview starting in fullscreen, but I always have to press o to get it appear clear.

hmm

**Comment by 0pLuS0** [comment]
I got the PNG ICC profile error again in 5.0...

I've moved on to another app, maybe one day you'll figure out why this error...

GL... :)
