### ISSUE TITLE
Option to save image after rotate/flip/etc action

### ISSUE THREAD

**Issue by dandepeched** [jurplel/qView#457]
This is basic feature which I'm surprised to find missing from the app. This can be implemented as an option in Settings (either user wants to save image automatically after rotation or not).

**Comment by WladyX** [comment]
Would also love this feature!

**Comment by r57zone** [comment]
A very useful feature when viewing photos, they often need to be expanded when photographing on a phone. The standard viewer can do this and it would be cool to see this in qView and allow the "save rotation on press key rotation" option.

Set image as wallpaper desktop and auto save image after rotation will finally completely replace the standard image viewer with qView. That would be great. Thanks to the authors for such a wonderful program and support.

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.
