### ISSUE TITLE
Separate option for slideshow sorting order

### ISSUE THREAD

**Issue by nmondal** [jurplel/qView#459]
Hi, 
I stumbled upon this and I must admit - qView is awesome.
It works for me in every possible way - gifs work, the image zooming works - everything works.
The only feature I miss is random image browsing.
Now one can argue that one can fix it by changing the file sorting order.
But bear with me - that changes the global preference.
What I want - and people want - is on different open image windows - having different order.
Of course there is a global order.
But once you open an image there should be some action to open next random image from the same folder.

Honestly, I used to be using Xee - when I was using my mac. Now I am in Zorin OS and loving every bit - almost - apart from the EOG - and I love qView.
This is the only thing that is missing.
P.S.
I have forked the project - but I have no clue about QT and the qt creator installation failing due to bad bandwidth.
If nothing I would raise a PR and fix it myself if time permits.
Thanks again for the awesome project.

**Comment by kleenkanteen** [comment]
Sounds like a meaningless feature

**Comment by nmondal** [comment]
> Sounds like a meaningless feature
Why you think so? Xee has it and honestly qView is a nice substitute for Xee. So.. I think it is  great feature to have.
Not much work anyways under the hood.

**Comment by Hrxn** [comment]
What? I think this feature is perfectly legitimate..

**Comment by vassudanagunta** [comment]
It totally makes sense for fullscreen slideshows... something that you might run at a birthday party or family reunion.

**Comment by kleenkanteen** [comment]
> It totally makes sense for fullscreen slideshows... something that you might run at a birthday party or family reunion.

What kind of person has fullscreen slideshows during a gathering? Lol.

Use your arrow keys to get a random picture. That's equivalent.

**Comment by Hrxn** [comment]
Not equivalent, because it's not random, d'oh..

**Comment by vassudanagunta** [comment]
@Hrxn, 

@kleenkanteen [is just a troll](https://github.com/jurplel/qView/issues/446#issuecomment-988202176). His self-worth is based on being arrogant and snarky. Sad.

**Comment by kleenkanteen** [comment]
@vassudanagunta Ironic you're the one calling me snarky when you made a snarky comment in the other post. Just because your feelings are hurt doesn't make the other person bad 😢

**Comment by needz** [comment]
It would be nice to just add a right-click option for Slideshow separately, so image browsing can be sorted by name and slideshow can be shown in random order. Now, the preference option works for both image browsing and slideshow, which is inconvenient.

**Comment by jurplel** [comment]
Wow this issue got kinda spicy. I think this is a good idea, probably coupled with some sort of UX change where the sorting mode is changed per-window in a context menu or something (currently things are a bit too deep in the preferences generally). It is weird to think how this will work with saving/loading the state of this option though. that might really be the biggest obstacle to that specifically being implemented in a straightforward way.

For now though, qView has things that are more broken than this that should be addressed first.

**Comment by kleenkanteen** [comment]
@jurplel By things that are broken do you mean everything addressed in milestone 5.0? Do all the 5.0 open issues implicitly have a help wanted tag in case someone wants to propose a fix?

**Comment by jurplel** [comment]
I will probably drop some of the 5.0 stuff. At this point i'm going to b-line to a release and maybe move toward 6.0 stuff because it's pretty darn foundational...

If you want to propose a fix to a 5.0 thing I will probably add it but it would be best to let me know first in case i wrote a horribly vague issue or something

**Comment by nmondal** [comment]
> Wow this issue got kinda spicy. I think this is a good idea, probably coupled with some sort of UX change where the sorting mode is changed per-window in a context menu or something (currently things are a bit too deep in the preferences generally). It is weird to think how this will work with saving/loading the state of this option though. that might really be the biggest obstacle to that specifically being implemented in a straightforward way.
> 
> For now though, qView has things that are more broken than this that should be addressed first.

That is precisely what I was thinking.

**Comment by nmondal** [comment]
@jurplel 
There is a simpler way of achieving the random next.
Do not have a setting in the first place - ( rather that browse setting - do not use it ).
Suppose "space" bound to the key as the next random image.
So all we need to do is get all files and selected next random one.
This is sampling w/o replacement ( just impl is that way).
Get a better chaotic random generator - and it would just work. 
This gives two different way to browse randomly - but at the same time I believe people would not mind it.

**Comment by jurplel** [comment]
> @jurplel There is a simpler way of achieving the random next. Do not have a setting in the first place - ( rather that browse setting - do not use it ). Suppose "space" bound to the key as the next random image. So all we need to do is get all files and selected next random one. This is sampling w/o replacement ( just impl is that way). Get a better chaotic random generator - and it would just work. This gives two different way to browse randomly - but at the same time I believe people would not mind it.

Yeah that is definitely doable

**Comment by marcelismus** [comment]
I would also find a random function for slideshows very useful.

**Comment by jurplel** [comment]
As hard as it is to do it, I am going to close this since I just don't see myself ever getting to it.

**Comment by nmondal** [comment]
@jurplel .. again thanks for the awesome viewer!
I had like one problem with it, the random order view was slow, for a folder having 1000s of images.
I have a folder having more than 7,000 images.
Now, in the latest version - it seems the performance has been massively improved.
Not sure how it happened or you explicitly worked or not, but it is massively improved.
