### ISSUE TITLE
Animated WebP frames don't dispose

### ISSUE THREAD

**Issue by brian6932** [jurplel/qView#461]
**Environment:**
- OS: Windows 10
- qView version: 4.0

**Information:**
Open an animated WebP file with frame disposal in a web browser like Firefox or Chromium, and compare
[Sample animated WebP file with frame disposal](https://www.gimp-forum.net/attachment.php?aid=3324)

**Comment by Serge45** [comment]
It seems a Qt bug, there's a related [stackoverflow post](https://stackoverflow.com/questions/53474445/qmovie-webp-frame-stutters). I've tested with Qt 5.12.9, the issue still exists. But if I rebuilt qView with Qt 5.15.2, it looks good:
![螢幕快照 2021-12-11 上午12 16 38](https://user-images.githubusercontent.com/2656666/145606710-cc44d32f-2158-4c77-ad70-5cc257ff74e0.png)

**Comment by jurplel** [comment]
Thank you for debugging this! Since the next version will be built with 5.15.2, this should fix itself.
