### ISSUE TITLE
Can I sort by the file explorer's setting?

### ISSUE THREAD

**Issue by bolieriniefu** [jurplel/qView#463]
My different folders have different sorting, can I make the qView use the file explorer setting? Thank you.

**Comment by jurplel** [comment]
This would require platform-specific code for macOS and Windows, and is probably largely impossible on Linux without DE integration. So, it is a bit much to add this.

**Comment by bolieriniefu** [comment]
> This would require platform-specific code for macOS and Windows, and is probably largely impossible on Linux without DE integration. So, it is a bit much to add this.

Okay thank you.
