### ISSUE TITLE
Turning off "Save recent files" has no effect

### ISSUE THREAD

**Issue by zx8** [jurplel/qView#471]
**Environment:**
- OS: macOS 12.1 Monterey
- qView version: 4.0

**Information:**

- Go to `qView → Preferences → Miscellenaous`
- Uncheck `Save recent files`
- Observe that recent files still appear in the `File → Open Recent` menu

**Comment by zx8** [comment]
Never mind, I see it has been fixed (but not yet released) in https://github.com/jurplel/qView/commit/6a48fee7cb39918747fcac863ee01a0b65c4adec

**Comment by jurplel** [comment]
Thank you!
