### ISSUE TITLE
Unnecessary error dialog after deleting last image in a folder (when loop through folders is disabled)

### ISSUE THREAD

**Issue by vassudanagunta** [jurplel/qView#472]
### To repro

1. Open an image in a folder with multiple images.
2. Disable qView `Loop through folders`.
3. Advance to the last image in the folder.
4. Delete the image (i.e. `Move to Trash` command)

The image will be deleted. But instead of showing the previous image or just showing no image, the following modal dialog appears:

<img width="605" alt="Screen Shot 2022-01-13 at 9 24 58 PM" src="https://user-images.githubusercontent.com/2830093/149459116-dbdca0c0-f244-48c0-9f19-4f887d2713b5.png">

Apparently it is trying to open the *next* image that does not exist. After clicking on `OK`, the dialog disappears and you are left with a blank window. You can go to the previous image.

### Expected behavior

When  `Loop through folders` is disabled, you could do any of the following, though A or C is my preference.

- **(a) Show nothing.** This is the best behavior when culling a folder of images of unwanted images. It's good to know that you've reached the end. 
- **(b) Show the previous image.** I think most image viewers do this. The problem is it's not obvious that you deleted the last image and you are now looking at a prior photo not the next photo. Say you are reviewing a folder of photos, deleting bad or redundant shots. Whenever you delete an image the next one is shown for your next decision. But if you reach the last photo (unbeknownst to you) and delete it, it will show you the prior image. You are likely to think: *"Oh, another duplicate of a shot I already have. Let me delete that."* Pretty soon you've deleted a bunch of photos you had previously decided to keep. Yikes!
- **(c) A preference setting letting the user choose**, e.g.:
   ```
     ▢ Loop through folders
     ✓ Go to previous image when last image in folder is deleted
   ```
   Setting grayed out if `Loop through folders` is enabled. 

### Environment
- OS: macOS 12.0.1 Monterey
- qView: Nightly 2021-05-19.1

**Comment by jurplel** [comment]
Confirmed. Not sure if you noticed, but there is an option to pick what to do after deletion: 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/10716694/149584296-e1b81bcb-bd21-47bc-be6f-06255080eb2c.png">

**Comment by vassudanagunta** [comment]
I'd want it to Move Forward after deletion, and only do nothing if it can't move forward. I take it that's what you mean? i.e. It would try to do what is selected in the `After deletion` setting, and only do nothing when it can't. That's perfect IMO.

**Comment by jurplel** [comment]
Yes I would consider that the desired behavior.

**Comment by jurplel** [comment]
Doesn't appear to be present in the latest builds
