### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by aicioara** [jurplel/qView#474]
Hello. Thank you for working on this project. I am seeing that the latest release (4.0) is from 2020 and I was hoping to get a fresher update that includes the move to trash action (https://github.com/jurplel/qView/pull/427). Is this something that is easy to do?

**Comment by jurplel** [comment]
It is in progress! I have been just fixing some last-minute issues and working on the distribution process. It will definitely be done today.

**Comment by jurplel** [comment]
done!
