### ISSUE TITLE
macOS file dialog permission loop

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#475]
**Environment:**
- OS: macOS Monterey (Apple silicon)
- qView version: 5.0

**Information:**
File dialog asks for access permission to use folders repeatedly: 
<img width="355" alt="image" src="https://user-images.githubusercontent.com/10716694/149609433-3784fdf2-328a-4a6a-89ee-c4ce73741a2b.png">

Didn't notice/hard to debug because it doesn't show up when compiling in qt creator.

Not sure if M1 specific: Running with Rosetta 2 does not fix it.
Qt 5.15.2 build works fine, only qt 6.2.2 build is affected.

Giving full disk access explicitly does not fix the issue.

Sometimes I open qView and the issue just doesn't happen?

This may go the way of the QTBUG before long

After testing x86_64, arm64, and universal builds with 6.2.2 locally, I can confirm that only universal builds seem to be affected by this issue.

Would be interested to know if this happens on Intel machines as well

**Comment by climbbike** [comment]
Same issue here. Also M1 Mac.

**Comment by vassudanagunta** [comment]
Confirmed on my M1.

**Comment by jurplel** [comment]
Qt bug report: https://bugreports.qt.io/browse/QTBUG-99894

**Comment by jurplel** [comment]
Ok, since this issue is so unacceptable I made an alteration to this release. There is now a separate Intel and arm64 download. You can get the arm version here: https://github.com/jurplel/qView/releases/download/5.0/qView-5.0-arm64.dmg

**Comment by jurplel** [comment]
Scratch that. I ran into an issue with the arm64 dmg and found that it wouldn't open without running `xattr` to remove `com.apple.quarantine`. After googling for way too long (is it just me or is googling Apple problems harder than Linux/windows/android? Seems like an endless sea of useless articles overshadows good information), I found that M1 macs require code to be signed. Sure enough, putting an empty signature in solves the issue. 

I then thought, what if the original issue was caused by the same lack of signature? Sure enough, signing the universal binary fixed the issue!

**Comment by jurplel** [comment]
I will wait for confirmation from someone else before I close the issue.

**Comment by climbbike** [comment]
well, I only got the "access files in your downloads folder" popup once now but now I have a new one
![warning](https://user-images.githubusercontent.com/5872570/149694133-4e4e6bcb-1974-4d51-8a6d-a36347f0d300.jpg)

**Comment by jurplel** [comment]
You have to right click and press open to pass that.

**Comment by climbbike** [comment]
yeah, I'm used to that. but in this case it was coming back every time I opened it. BUT . . . now it seems okay . . . yeah. seems to be working now.

**Comment by jurplel** [comment]
hooray

**Comment by vassudanagunta** [comment]
> I will wait for confirmation from someone else before I close the issue.

I can't figure out where to get the latest macos build. I don't see a 5.0.1, and the nightly is from Friday.
