### ISSUE TITLE
"Skip this version" option on upgrade dialog

### ISSUE THREAD

**Issue by vassudanagunta** [jurplel/qView#477]
Since I can't use qView 5.0 because of #475, every time I open qView 4.0 or older nightly build I get the upgrade dialog.

### suggestion
1. Maintain a list of installed or skipped versions somewhere.
2. When qView starts up and does its update check, it won't show the dialog if the new version is in the list.
3. If the user selects "Skip this version" in an update dialog, that new version number is added to the list.
4. Also, any version the user has run before is also in the list. This way I can run an older version of qView without it asking me to upgrade every time, because it can see I already have the new version.

**Comment by jurplel** [comment]
You can disable update checking
<img width="581" alt="image" src="https://user-images.githubusercontent.com/10716694/149672465-c05f5832-0598-4422-a870-c2d68bb751ff.png">

I will solve the file dialog issue ASAP.
