### ISSUE TITLE
More RAW Files Types please

### ISSUE THREAD

**Issue by liambede** [jurplel/qView#481]
greetings!

Would really like to see support for more raw file types. I specifically noticed that .mrw files from my Minolta digital camera are not able to be opened. I was previously using Image Glass and that was able to open these files no problem.

I hope this is not too niche of a request or too difficult to implement as then I could switch fully to qView!

thanks!

**Comment by jurplel** [comment]
You should try this image plugin (will require compiling on your own probably) https://gitlab.com/mardy/qtraw

**Comment by jurplel** [comment]
raw is now supported in 6.0
