### ISSUE TITLE
Update view on file update

### ISSUE THREAD

**Issue by timtroendle** [jurplel/qView#483]
It would be great if the view would detect changes in the file and update.

My workflow is: I create an image, open it in qView, I update the image (basically replace the file with a new version), and go back to qView. qView still shows me the old version of the image (that doesn't exist anymore on disk). Preview.app does detect the change.

qView: 5.0
OS: macOS 12.2.1

**Comment by vassudanagunta** [comment]
Native apps detect name changes or file moves, and usually follow a file even to the trash can. What you describe should only work if the app you use to update the image rewrites the same file, which is different from replacing a file with another using the same name.

**Comment by timtroendle** [comment]
I see, that makes sense. My workflow actually deletes the file first and then replaces it with a file with the same name. Preview.app will show the updated file -- considering what you said, this may be more like a quirk (bug) than a feature of Preview.app?

**Comment by kcris** [comment]
> Native apps detect name changes or file moves, and usually follow a file even to the trash can. What you describe should only work if the app you use to update the image rewrites the same file, which is different from replacing a file with another using the same name.

there are ways to monitor for file changes, with qt for example there is this old fs watcher

https://doc.qt.io/qt-5/qfilesystemwatcher.html

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.
