### ISSUE TITLE
qapng, qapngd, qavif, and qjpegxl should probably be included

### ISSUE THREAD

**Issue by brian6932** [jurplel/qView#484]
**Environment:**
- OS: Windows 10
- qView version: 5.0

**Information:**
I've had this issue for a long time, but haven't cared to report, since I don't use apngs much.
I know it's supposed to be supported, but for some reason, it doesn't work.
There might be a missing fta, or just Windows might be detecting mime types weird or something:
![image_116](https://user-images.githubusercontent.com/18603393/154302280-d3754518-14e5-496b-adf9-10fcb7acbc53.png)
To reproduce:
Open https://apng.onevcat.com/assets/elephant.png in qView on Windows

**Comment by jdpurcell** [comment]
This appears to be because the APNG library is no longer present in the "imageformats" folder with the 5.0 release. If I copy over "qapng.dll" from the 4.0 release, 5.0 is also able to play animated PNGs.

**Comment by gaiking-uk** [comment]
## +1
I'd also vote for this, or certainly "qapng" at least - so if APNG (animated PNG) support could be re-introduced to the master / latest release that would be great! 👍🏼

## Additional context
I am in search of a single, lightweight app that I can use to open any image files that Windows Photos can't... currently this means .webp and .apng [yes, I know it's a rare/odd format... I am not advocating for this format particularly, however I have had to inherit some animated png files and need an app that can handle these too, so if it's literally just a matter of included ```qapng.dll``` into the latest release then that's a win all round I think!

**Comment by EvanEdwards** [comment]
I can confirm the elephant image is animated properly using both qView versions 4 and 5 on Linux in a KDE install using AppImage.

**Comment by jurplel** [comment]
should be working on latest nightly now that i have a better method of deploying image plugins.
