### ISSUE TITLE
JPEG-XL files don't work

### ISSUE THREAD

**Issue by beingalink** [jurplel/qView#485]
**Environment:**
- OS: macOS 12.2.1
- qView version: 5.0

**Information:**
I created a jpeg-xl file based on `red.png` (see attachment) using https://squoosh.app/ with default settings for jpeg-xl (also attached). The resulting file can't be opened in qView (unsupported image format (error 3)), but works in firefox (when jxl support is enabled).

[red.zip](https://github.com/jurplel/qView/files/8170026/red.zip)

**Comment by novomesk** [comment]
I am not absolutely sure but I guess that some libraries needed by `libjxl.0.7.dylib` are missing:

- libbrotlidec.1.dylib
- libbrotlienc.1.dylib
- libbrotlicommon.1.dylib

**Comment by beingalink** [comment]
Yes, copying these libraries to `/Applications/qView.app/Contents/Frameworks` makes it work. I guess they will be added to the release build in the future? Thanks for your help!

**Comment by jurplel** [comment]
Sounds like a mistake on my part. Duly noted.

**Comment by jurplel** [comment]
this should be fixed with my recent deployment changes, present when 6.0 releases
