### ISSUE TITLE
"Window matches image size" doesn't actually make the window match the image size

### ISSUE THREAD

**Issue by kin-patsu** [jurplel/qView#495]
**Environment:**
- OS: Windows 11 21H2
- qView version: 5.0

**Information:**
Opening any picture smaller than the screen always seems to resize the window (and the picture), zooming it despite what set in the settings. I'm unsure if it would help, but I'm using a 4k screen

Example: 
![image](https://user-images.githubusercontent.com/19828171/164573082-4f166903-2a49-49ca-a9d2-7adf4d19e99a.png)
Left, qView, right qimgv, both have the same 520x486 picture

**Comment by jurplel** [comment]
This is most likely the same poor high DPI behavior as many of the other issues

**Comment by jdpurcell** [comment]
Related to #374, just mentioning it for tracking purposes

**Comment by jurplel** [comment]
Yeah, closing this in favor of #495 since it has better documentation.

High dpi behavior should be made optional/reasonable in all cases
