### ISSUE TITLE
add background blur option in settings

### ISSUE THREAD

**Issue by safak45x** [jurplel/qView#498]
add background blur option in setting
![Screenshot_20220429_014859](https://user-images.githubusercontent.com/59151376/165861462-afd71e79-a573-40f4-9362-e78bac90e563.png)
s

**Comment by safak45x** [comment]
or a setting where we can use rgb color codes instead of hex code.

**Comment by jurplel** [comment]
This is pretty, I experimented with doing this but I decided against it. I will stick with that for now--apologies. Thank you for your suggestion.

**Comment by jurplel** [comment]
> or a setting where we can use rgb color codes instead of hex code.

you should be able to use the system color picker, which should let you pick with rgb?
