### ISSUE TITLE
qView Can't be Opened

### ISSUE THREAD

**Issue by metayyab** [jurplel/qView#499]
**Environment:**
- OS: macOS 12.3.1
- qView version: 5.0
- 
**Information:**
I am unable to open the app after installation, and I have already the message I received.

<img width="249" alt="Screen Shot 2022-05-06 at 4 13 28 PM" src="https://user-images.githubusercontent.com/22665102/167139598-d577956b-58ff-4d10-9664-3b881e472234.png">

**Comment by cronk005** [comment]
I am also having the same issue. ;-(

**Comment by cubuspl42** [comment]
I'm also having this issue. It doesn't seem like there's an easy workaround.

@jurplel Friendly ping, as this is a literal blocker on macOS.

**Comment by cubuspl42** [comment]
Sorry, that dialog actually _does_ have a workaround. You can go to _System Preferences > Security and Privacy > General_ and decide to open the app anyway. But not all users know about this possible workaround, so it's still a big deal.

**Comment by cronk005** [comment]
Actually this is not possible from what I can see. You have two choices:
Allow from App Store and Allow from App Store and identified developers.
This app is not listed as an identified developer so is rejected by the Mac
OS from installing.

Thanks,
Daniel


 live long & prosper


Daniel E. Cronk, LVT
PACS/Radiation Therapy Systems Administrator
(pronouns: he/him/his)

University of Minnesota - Veterinary Medical Center
1365 Gortner Avenue
Saint Paul, MN 55108

612.624.2784 (office)
612.625.1200 (radiology)



*My Hours of Operation: *
Mon: 7 am - 3:30/5:30 pm
Tu thru Thurs: 7 am - 3:30 pm
Fri: 3:30/1:30 pm

*Upcoming Time Off:*
Sept 1 thru Sept 25

**Comment by jurplel** [comment]
You should be able to work around it like so:
https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by asarkar** [comment]
We don't want to "work around" this issue, we would like it to be fixed such that it doesn't behave like a Trojan malware.

**Comment by jurplel** [comment]
> We don't want to "work around" this issue, we would like it to be fixed such that it doesn't behave like a Trojan malware.

Well that would be nice, but I don't see a way to fix it without getting an apple developer license for $99/year, which is not worth it in my opinion. I am frustrated that Apple apparently keeps making it harder for open source app developers to not buy the license.
