### ISSUE TITLE
ColorSync Profiles?

### ISSUE THREAD

**Issue by hyungsongnam** [jurplel/qView#500]
Hello,
Could I ask if color calibration profiles are in the plans?
I just got a P3 display, and now the color seems over-saturated (download image file below to see comparison of macOS Preview and qView, in Firefox anyhow, both look the same).
Thank you for the great work, qView is very useful for me.
Sincerely,
Hyung-song Nam, PhD

![Screen Shot 2022-05-27 at 6 53 29 PM](https://user-images.githubusercontent.com/36607862/170803335-6478f662-de8d-4074-9147-cc581097443e.png)

**Comment by Andreas0602** [comment]
I agree, this is an important feature. It would be great if it could be added.

**Comment by hyungsongnam** [comment]
Compiled the recent code with the colorspace feature. Works great! Thank you!
Sincerely,
Hyung-song Nam, PhD
