### ISSUE TITLE
Can not open files in Samba shares

### ISSUE THREAD

**Issue by FBachofner** [jurplel/qView#504]
**Environment:**
- OS: Fedora 36, Cinnamon
- qView version: 5.0-1

**Information:**
I just tried qView in Fedora 36 running CinnamonDE

Where other image viewers such as Eye of Mate, gThumb and XNViewMP can open files from a SMB share, qView can not.

qView was set as the default image viewer and was able to automatically open LOCAL files when double-clicked in Nemo file manager.

However, browsing to a SMB share and douple clicking the file and/or right clicking and "open with" results in qView not doing anything.

**Comment by FBachofner** [comment]
If I try to open the file from Nemo, the error is:
```
Error occurred opening "MyImagesName.png":
File not found (Error 1)
```

If I try to open from within qView (Ctrl-Shift-O), the error is:
`Error 301: Protocol "smb" is unknown`

**Comment by jurplel** [comment]
Closing this since it's old, feel free to reopen
