### ISSUE TITLE
Show Thumbnails

### ISSUE THREAD

**Issue by riley-x** [jurplel/qView#508]
It would be great if there was the option to show thumbnails as a navigation aid. A scrollable gallery at the bottom like what Mac finder does would be cool:

<img width="579" alt="Screen Shot 2022-09-15 at 11 11 49 AM" src="https://user-images.githubusercontent.com/29797357/190441184-08c49370-b4b7-4e44-b21e-eef422ed8836.png">

**Comment by tehmasterer** [comment]
+1

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.

**Comment by Arcitec** [comment]
It's the most important feature for me, to find any image rapidly when a folder contains lots of different things.

qView is awesome, but this single missing feature meant I have to use qimgv instead:

https://github.com/easymodo/qimgv

I can recommend qimgv. It's not pretty. But it's decently fast and very configurable.

**Comment by jurplel** [comment]
`qimgv` is great!

**Comment by SekiBetu** [comment]
If qView had this feature, it could replace imageglass in my use of it
