### ISSUE TITLE
qView random image surfing is slow on a folder having moderate no of images ( 4,000+)

### ISSUE THREAD

**Issue by nmondal** [jurplel/qView#509]
**Environment:**
- OS: [Ubuntu 20.04, Zorin OS]
- qView version: [5.0]

**Information:**
Given a folder with reasonably moderate no of files ( 4,000 ) - next and previous image load is very slow.
Given I do have 32 GB ram.. this is a spot of bother.
Mirage can do that instantly.
qView takes 3 secs to load.
Also the random next and previous functionality takes similar time.

I think upto 100,000 images the next and previous with random load can be made instantaneous.

Again, fantastic work, I know we are asking for much, but I think it is possible.

**Comment by secretfork** [comment]
I can confirm this. Even right now i was browsing a folder of ~220 files (folder size roughly ~620mb) and it takes ~1 second every time i move to the next image. Might not sound much, but if you're constantly flipping through them and need to move further then just the next adjacent image it adds up.

**Comment by dmlemos** [comment]
It is happening to me with a folder of only 6 files. Switching through files takes 2-3 sec depending on the image. In some cases only 1.5 sec.
Image resolution is 3456x4608 YCbCr H2V2 JPEG. Using macOS Big Sur 11.7
For comparison Xee3 doesn't have this issue at all.
