### ISSUE TITLE
Carousel feature wanted

### ISSUE THREAD

**Issue by desbest** [jurplel/qView#510]
Please add a carousel feature, so I can slide across all the open images to move from left to right, while one of the multiple open, is selected.

```
           ___________
           |               
           |               
           |__________|

|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
```

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.
