### ISSUE TITLE
unable read image data

### ISSUE THREAD

**Issue by vmtest888** [jurplel/qView#511]
**Environment:**
- OS: Windows 10
- qView version: 5.0

**Information:**
unable read image data

![98C73CBE-3F51-46a1-95B4-28200D7D4C13](https://user-images.githubusercontent.com/26427035/192995837-61bd9ed5-2f65-4008-a7ae-00082baaccc6.png)

![C697521F-6225-4d80-A6AE-D2834BFB5361](https://user-images.githubusercontent.com/26427035/192996064-0ec125fe-5da4-4095-8dfe-97516c98972f.png)

[npc_192.zip](https://github.com/jurplel/qView/files/9673257/npc_192.zip)

**Comment by jurplel** [comment]
Closing because this is an old issue. Sorry I didn't get to it sooner. Feel free to reopen if you would like to debug it.
