### ISSUE TITLE
Is there any plan add customize mouse actions?

### ISSUE THREAD

**Issue by s65d4fs654dg** [jurplel/qView#512]
1，mouse button customization, like left click for next image or click right edge area for next image, middle click for original size, etc. i use ahk script with qview for mouse action but not work well.
2，mouse pan option, hover mouse move to quick navigation.

may be small issue:
Window will resize when open a image, can't keep the size of last time. 

other:
please add scale factor to titlebar text when it set to Verbose.

**Comment by jurplel** [comment]
Scale factor to titlebar text is planned.

>  Window will resize when open a image, can't keep the size of last time.
not sure about this--i think it might be fixed.

I do not plan to currently add this feature, so I will close it since there are too many open issues right now.
