### ISSUE TITLE
Speedup while using large folder

### ISSUE THREAD

**Issue by RoyBellingan** [jurplel/qView#516]
I noticed the function https://github.com/jurplel/qView/blob/eee6b693e3694876950bada0d47756803b2aed14/src/qvimagecore.cpp#L256

Not only can be slow in large folder, but is called two times for each picture shown.

I do think there is no reason for it to be called if nothing is changed, so i propose to add this code on the line

https://github.com/jurplel/qView/blob/eee6b693e3694876950bada0d47756803b2aed14/src/qvimagecore.cpp#L264

As a side effect this will avoid the reshuffling of the set each time, which I think is not the intended action, else each time you reshuffle, you can see again the same picture over and over, or you can jump most of them and be immediately at the end...

```
    {
        //No idea how to call this function when settings are updated
        static auto oldSortMode = sortMode;
        bool force = false;
        if(oldSortMode != sortMode)
        {
            oldSortMode = sortMode;
            force = true;
        }
        
        //FIXME or check if the sort method changed
        if (!force || lastDirInfo == dirInfo)
        {
            //no need to do nothing except advance current file positon ptr
            currentFileDetails.loadedIndexInFolder = currentFileDetails.folderFileInfoList.indexOf(currentFileDetails.fileInfo);
            return;
        }
    }
```

For more info I wrote a bit there https://github.com/jurplel/qView/issues/514

If you want I can do a pull request, but for that case I think is not worth the added complexity.

**Comment by jurplel** [comment]
`updateFolderInfo`, in the latest builds, is indeed not called every time as desired.
