### ISSUE TITLE
unable to open JPEG XL

### ISSUE THREAD

**Issue by superbonaci** [jurplel/qView#535]
Unable to open jxl:

[animation-woods.jxl.zip](https://github.com/jurplel/qView/files/10240437/animation-woods.jxl.zip)

**Comment by jurplel** [comment]
what OS? what version? how did you download it?

**Comment by superbonaci** [comment]
Installed for macOS with brew (using Apple M2)
https://formulae.brew.sh/cask/qview

**Comment by jurplel** [comment]
possibly a distribution issue. Putting the plugins in for qview 5.0 was just done manually since it is annoying to automate

**Comment by jurplel** [comment]
Duplicate of #485
