### ISSUE TITLE
Switch to qt6

### ISSUE THREAD

**Issue by b3sser** [jurplel/qView#539]
According to the changelog, version 5.0 added qt6 support. However, qview on my system still uses qt5.

The system has been freshly set up a few weeks ago and got qt6 right from the start, so it's not a remain of an old configuration.

I use qview 5.0-1 on Arch Linux and according to my package manager, it depends on qt5.
My system has both qt5 and qt6 installed (because of mixed dependencies).

Are there any extra steps I need to take to have qview use qt6?

**Comment by jurplel** [comment]
So, I think the AUR package still uses qt5, but there's no reason for this, you could just compile it with qt6 just as easily.

**Comment by jurplel** [comment]
So, I was going to switch but it doesn't make a lot of sense right now to change the main package to that, since there is no kimageformats and it looks bad on KDE without a platformtheme.

Someone can feel free to make a qview-qt6 AUR package for now--just use qt6 dependencies and run qmake6 instead.

**Comment by FreezyLemon** [comment]
Would you consider updating the AUR package now that KDE 6 has released to the Arch repositories? I'm not sure what the issue with kimageformats is, but a Qt6-based version of that package is out too

**Comment by Hrxn** [comment]
There's also this fork which apparently is already on Qt 6

https://github.com/jdpurcell/qView

**Comment by jurplel** [comment]
> Would you consider updating the AUR package now that KDE 6 has released to the Arch repositories? I'm not sure what the issue with kimageformats is, but a Qt6-based version of that package is out too

Yes definitely
