### ISSUE TITLE
Very laggy switching between images

### ISSUE THREAD

**Issue by lonely701** [jurplel/qView#540]
Environment:
- OS: Windows 10 22H2
- qView version: 5.15.2 (x86_64)

Information:
The response is significantly slower than Windows 10 built-in Photos app and Honeyview. When opening an image in a folder with thousands of images (in my case 4397 images, 1920 by 1080 PNG), it is too laggy to use. The UWP Photos app uses very low-res images when fast switching between photos, while Honeyview shows full-res images and is still crazy fast. However, Honeyview's color management is not very good, so I am looking for an alternative.

**Comment by jurplel** [comment]
This should be fixed in the latest builds.
