### ISSUE TITLE
Can you add a bird 's-eye view to the bottom right corner of the view?

### ISSUE THREAD

**Issue by libaineu2004** [jurplel/qView#553]
Can you add a bird 's-eye view to the bottom right corner of the view?
For example, like this picture:
![缩略图](https://user-images.githubusercontent.com/11898277/210537793-d1e51025-9ce6-45a9-8d02-5fddb2703964.png)

**Comment by jurplel** [comment]
In the interest of reducing the number of open issues, this is not in my vision for qView and I don't plan to implement it. Feel free to fork and add this, of course.
