### ISSUE TITLE
Segmentation fault by holding an arrow key

### ISSUE THREAD

**Issue by es20490446e** [jurplel/qView#567]
**Environment:**
- Manjaro Linux stable
- qView 5.0

**Information:**
While in a folder with multiple images, if you just hold an arrow button for a while, the program crashes with "segmentation fault (core dumped)".

[Woops!](https://media.giphy.com/media/13d2jHlSlxklVe/giphy.gif)

**Comment by jdpurcell** [comment]
This is probably the same as #490 in which case it's fixed in the nightly builds. The most recent nightly build is [here](https://github.com/jurplel/qView/actions/runs/3920964991#artifacts) (Artifacts section) if you'd like to try it.

**Comment by es20490446e** [comment]
Testing...

**Comment by es20490446e** [comment]
Fixed, but it has another one:
https://github.com/jurplel/qView/issues/568
