### ISSUE TITLE
No CROP function?

### ISSUE THREAD

**Issue by Shituation** [jurplel/qView#575]
Its the only thing keeping me from using it.

**Comment by jurplel** [comment]
I do not plan to implement this currently, so in the interest of reducing the quantity of open issues, I will close this. Thank you for your suggestion nonetheless.

**Comment by IT-Tool** [comment]
Anyway it would be nice to see this feature added to the program one day!

**Comment by IT-Tool** [comment]
@jurplel It would be wonderful if this feature could be added to the program at some point in the future.

**Comment by jurplel** [comment]
Since last year, I think I am more open to this feature for the future, bu I am focused on improving core functionality first.

**Comment by MerryMacMapface** [comment]
That would be great! e.g. ImageEye (Windows only) has this feature perfectly and I won't miss it.

**Comment by vassudanagunta** [comment]
@jurplel I suggest a more powerful thing would be for qView to be the best renderer, but be able to send the image to another tool (#579, and maybe also #663 as i suspect its mostly the same code). Or maybe implement macOS's sharesheet?

**Comment by LaVenganzaArchivo** [comment]
qimgv has crop function, can run personal scripts from key shortcuts.
