### ISSUE TITLE
Window to match image size when zooming

### ISSUE THREAD

**Issue by Andreas0602** [jurplel/qView#582]
It would be great if you could implement a feature so that the window will match the image size when zooming, i.e. the window shall become larger when you zoom in, and the window shall become smaller when you zoom out.

**Comment by jurplel** [comment]
In the interest of reducing the number of open issues dramatically, I do not plan to implement this currently so I will close the issue. Thank you for your suggestion nonetheless.

**Comment by vassudanagunta** [comment]
Also I think I have it covered in #460.
