### ISSUE TITLE
Folder ith 1,000 jpegs, qview crash

### ISSUE THREAD

**Issue by uzilover45** [jurplel/qView#585]
**Environment:**
- OS Windows 11
- qView version: 5.0 - Qt 5.15.2 (x86_64)

**Information:**
Hi
I have a folder with over a thousand jpegs. Click on one. qview takes a while to open and when it does i can not click to the next one or go back as qview hangs and does not respond. 

Windows Photos opens all the jpegs and i can cycle through no problem 

Any ideas or setting i shoudl change?

**Comment by jdpurcell** [comment]
I would recommend trying the latest nightly build ([download instructions here](https://github.com/jurplel/qView/issues/479#issuecomment-1379644622)). There were somewhat recent code changes (after the 5.0 release) that make it behave much better with large folders.

**Comment by uzilover45** [comment]
Hi,
That nightly build works perfeclty. Thank you

**Comment by jurplel** [comment]
Closing since I just need to draft a release
