### ISSUE TITLE
File loading operation is abnormally slow.

### ISSUE THREAD

**Issue by warkene2** [jurplel/qView#586]
**Environment:**
- OS: Windows10_Home_22H2 Build_19045.2846
- qView version: 5.0-win64.exe

**Information:**
File loading is abnormally heavy.
Even from an external HDD, there is a lag of about 1 second, and reading from a network drive takes more than 10 seconds, making it unusable.
I just want to comfortably view images in WebP format, but why...

**Comment by warkene2** [comment]
Sorry, I tried using the nightly version and it improved the loading speed, but now I can't load avif format files... what can I do about this?

**Comment by jurplel** [comment]
Closing since it's addressing a resolved issue
