### ISSUE TITLE
Have option to select parts of an image to then copy it

### ISSUE THREAD

**Issue by Miepee** [jurplel/qView#597]
A feature I miss greatly from Irfanview that so far no other image viewer in linux has replicated for me, is the ability to select an area from an image, and then copy the selection as a buffer. Basically as a short way of cropping an image. Currently the workarounds are either: zoom into a section, and then make a screenshot with a snipping tool, but that won't have the same results or open the image in an image editor, crop the image, copy the image, then close the image editor, which takes too long.

**Comment by jurplel** [comment]
This would indeed be cool but is out of scope for now. I intend to keep qView very minimal and not add many features for now.

**Comment by Miepee** [comment]
Understandable.
Just out of curiosity, if someone would send a PR that implements that feature, would that have chances of getting merged, or would that get closed for the same out-of-scope reasons?

**Comment by jurplel** [comment]
That's a great question.  I think that adding a selection box as a feature at all would require a significant amount of UI planning. I would need it to be done in some way that doesn't compromise the current interface of the program in any way, which seems really difficult. I am not against adding it in general but it would be a lot of work for a small feature.
