### ISSUE TITLE
Extremely slow work in large directories

### ISSUE THREAD

**Issue by pursvir** [jurplel/qView#598]
**Environment:**
- OS: Fedora Workstation 38
- qView version: 5.0

**Information:**
In a directory with about 9000 photos it takes about 3 seconds to open an image, and about 6-7 seconds to move between with arrow keys. And at the time of moving to next/previous file qView also utilizes 100% CPU.
In a directory with about 3000 photos, 1 second to open and about 1,5 seconds to move between, and about 60% CPU at that moment.
I've tried repo package, rpm release from GitHub, flatpak and even AppImage. All suffer from it, though I have a powerful CPU.

**Comment by jurplel** [comment]
closing--reopen if you have issues on latest nightly.
