### ISSUE TITLE
issue rendering qView 5

### ISSUE THREAD

**Issue by 3xploiton3** [jurplel/qView#600]
**Environment:**
- OS: [ Windows 11 ]
- qView version: [e.g. 5]

**Information:**
reference:
https://www.ups.com/assets/resources/webcontent/images/ups-logo.svg

chrome stable
![image](https://github.com/jurplel/qView/assets/19517680/a619f7f4-ec80-4583-b754-b22d5743ceaa)

from qView
![image](https://github.com/jurplel/qView/assets/19517680/2bac3169-3821-41e1-a834-598abc58c9b7)

**Comment by jdpurcell** [comment]
With the latest [nightly build](https://github.com/jurplel/qView/issues/479#issuecomment-1379644622), this problem still affects the 32-bit Windows build, but the 64-bit Windows build renders it properly. So I'm guessing it's a Qt issue that was resolved somewhere in their 6.x releases.

**Comment by jurplel** [comment]
Thank you for the debugging @jdpurcell. Since there's not much to do here besides update the Qt version, I will close the issue for now.
