### ISSUE TITLE
Jump to Random Image (and n images ahead/back)

### ISSUE THREAD

**Issue by EvanEdwards** [jurplel/qView#601]
It would be nice to have an option to jump to a random image in the set of images being cycled through.  Even if it were an optional Shortcut.   In addition, jumping either 10 images or 10% through the list with PageUp and PageDown (or Shift+Left/Shift+Right) would be useful.

| Key | Effect |
| --- | --- |
| Right | Next image in directory/set |
| Left | Previous image in directory |
| r  | Jump to random image in directory |
| PageUp | Jump 10 images back (or 10% of image set back) |
| PageDown | Jump 10 image ahead (or 10% of image set ahead) |

**Comment by jurplel** [comment]
This is a great idea, but since I am trying to aggressively keep the open issue count down I am going to close this since I don't plan to implement it for now.

**Comment by jdpurcell** [comment]
@jurplel FWIW I just implemented Go -> Random File in my fork. Perhaps not suitable for the official qView at this time because I used `QRandomGenerator` which isn't available in Qt 5.9. Mentioning #67 for tracking purposes.
