### ISSUE TITLE
——作者你好，为了qView，特地感谢和赞美你，qView是极其优秀的看图软件

### ISSUE THREAD

**Issue by gemkeeper** [jurplel/qView#605]
作者你好，我是中国的一个用户，
中国有个软件叫“美图看看http://kankan.meitu.com/”，
这是一个非常优秀的小软件：耗费内存很小，速度很快，没有BUG
但是，它太古老了，所以不支持 最新、最先进的的3种类型的.jxl(JPEG XL)   .avif   .webp2  以及.webp  格式图片，

为了找到能够浏览最新的这4种格式的图片的软件，我花了3天的时间，在网上搜索，下载，安装，试用了 10多个软件，
遗憾的是：它们全部都有各种缺点：耗费内存大，操作不方便，设计不够人性化，使用不方便。

——只有你研发的qView非常完美，占用内存很小，比“美图看看”更加节省内存，左右切换速度最快，窗口能够自动适应图片，各种细节设计非常人性化、能够关联常见图片类型，鼠标双击图片即可使用打开qView浏览，
——总之，太完美了！惊叹！
可以看出：你一定是极其用心认真地研发、调试，才做出这么优秀、贴心、易用的软件！

qView比另外2个著名的软件 nomacs 64bit和XnView MP 64bit 更加 节省内存！耗费内存几乎只有他们的20%，仅使用小于25-30M，体积也更小！速度也更快！
你太优秀了！我特地向你表达感谢和赞美！
祝愿你能够一直 把这个软件 保持、维护、研发、存在、发展下去！
你是上帝派来人间的天使！
——————————————
1，偶然发现１个BUG：如果是在一个 只有 十几张图片的文件夹里，鼠标双击图片 默认使用qView打开，没有任何问题，一切都很都好。
　　但是，如果是在 一个 具有几百张或者一千张图片的 文件夹里，鼠标双击图片 默认使用qView打开，则每切换1张图片，qView都会卡住 好几秒，标题提示“未响应”
——已经在设置里  调试 分别试验过 “预加载”里选择“禁止”或“预加载下一张”，也分别　勾选　和　取消“循环浏览文件夹”，
都没能解决这个问题，
不知道是哪儿的原因，
作者朋友 有空可否检测一下？
————————
2，可否增加一个 可以自主选择的选项：当鼠标滚轮滚动 缩放图片时，软件窗口的长宽，随着图片尺寸的缩放，也一起自动缩放，窗口的长宽刚好适合图片缩放的的长宽（但是不超出 电脑屏幕的长宽），而不是一直保持固定不变的长宽。
让用户可以自由选择设置。
——这条需求本来是用于 很长高度的网页文章的长条截屏图片使用的，——但是，这条需求已经可以无视了，可以作废，
——因为我在qView的设置仔细调试后，发现在使用时， 鼠标左键双击，能够实现下面3种模式的来回切换：
（1初打开的模式：第一次双击图片 打开qimgv软件窗口的狭窄模式，图片高度适应窗口高度，也就是电脑屏幕分辨率的高度。
2全屏模式：图片的尺寸宽度，得到100%的显示。
3窗口模式：图片的尺寸宽度，得到47%的显示，——这个宽度已经足够看清楚长条截图上的文字了，但是，如果改成把图片宽度100%地显示，则更好。）
之后 继续鼠标左键双击，就会在2和3这两种模式之间来回切换，

所以，这3种模式的切换，尤其是第3种模式：窗口模式，图片宽度显示47%，已经足够我日常使用了，
当然，如果第3种模式：窗口模式，图片宽度的尺寸，能改进成显示100%的宽度，（或者最好这个比例可以在设置选项里，让用户自定义选择设定数值）那么就更完美了！

**Comment by jurplel** [comment]
Thank you for your kind words!

來自谷歌翻譯：謝謝您的客氣話！
