### ISSUE TITLE
Properly handle cloud files on OneDrive (Windows)

### ISSUE THREAD

**Issue by crse** [jurplel/qView#607]
**Environment:**
- OS: Windows 11
- qView version: 5.0

**Information:**
Every time I open image offline file stored on OneDrive, qView will start preload every single image files in the OneDrive folder, which result OneDrive downloading every single cloud files in the folder. This often result qView to be not responsive.
Disabling `preloading` still result the same behaviour.

Expected behaviour:
qView open the selected image normally without OneDrive to download every single images.

**Comment by jurplel** [comment]
Can you confirm the same behavior doesn't happen with other image viewers?

**Comment by crse** [comment]
Windows 11 native Photos app: Only download one specific image I want to open.

ImageGlass: Downloads one specific image I want to open + another two images before and after the file image (based on alphabetical name sorting)

**Comment by jdpurcell** [comment]
This might be fixed on the nightly builds if it was related to the way 5.0 was querying MIME types.

**Comment by jurplel** [comment]
let me know if it's not fixed on nightly/6.0, and ill reopen this

**Comment by crse** [comment]
Can confirm, this problem is fixed on nightly version.
Thank you!
