### ISSUE TITLE
Freezes when folder of opened image contains a lot of other images

### ISSUE THREAD

**Issue by DaBlincx** [jurplel/qView#609]
**Environment:**
- Windows 10
- qView version: 5.0

**Information:**
If I want to open an Image in a folder with a lot of Images inside (50k images), then it takes forever to load and freezes.

![image](https://github.com/jurplel/qView/assets/80812233/bf50ca39-11e4-400a-9cb3-5b9b8eaf4d01)

i havent looked at the code but i assume, that it tries to load every image in the folder to create a smooth viewing experience. maybe only load the 10-15 images next to the initial image that was opened instead of checking everything. would be cool 👍

**Comment by jurplel** [comment]
This should be fixed in 6.0/nightly. I will release 6.0 imminently.

**Comment by jurplel** [comment]
let me know if it still presents on a newer version and ill reopen
