### ISSUE TITLE
Wayland crashes

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#611]
**Environment:**
- OS: Arch Linux with only Wayland
- qView version: 6.0

**Information:**
Caused by trying to query X11 information on a wayland-only machine.

**Solution:**
check `isPlatformX11` before doing X11 checks. Remember to make sure Qt6 works too.

**Comment by rezad1393** [comment]
hi
I am the one reporting that in archlinux aur.

a friendly suggestion:
on linux use the most recent toolkit specially when tracking changes in wayland or qt.

a lot of stuff have changed in wayland/Qt land recently.

most importantly for me is the fractional scaling.

like this issue with mpv that was not mpv issue per se but a wayland issue that needed to be fixed.
https://github.com/mpv-player/mpv/issues/9443

if you use qt5 you have to use only qt5 as qt6 changes somethings.

for example here a kde dev explains how qt6 and even qt6.6 changes thing vs earlier versions (5 and 6.5)
https://blog.broulik.de/2023/08/on-the-road-to-plasma-6-contd/

so trying to release a new version of software but not taking into account the new versions of toolkit changes, forces the developer to do twice the work (one for qt5 and one for qt6)

**Comment by jurplel** [comment]
On my personal machine(s), I actually use KDE Wayland on Arch. I assume since I have X11 installed as well, the issue wasn't present on my end.

I wanted to switch the AUR package to Qt6, but until Plasma 6 drops I am not sure it makes much sense to do so, since `kimageformats` has no official package and there is no Breeze style.

**Comment by Shaurya-Kalia** [comment]
I have an x11+wayland system, but use wayland and get the same error
`zsh: segmentation fault (core dumped) img.jpg`

**Comment by telans** [comment]
I can confirm 2a6bdfa1c076975aab7f80f7d76497af9ea1af86 fixes this issue for me. I too have an X11/Wayland system.

**Comment by telans** [comment]
Could we get a bugfix release for this?

**Comment by jurplel** [comment]
definitely. will get it out soon
