### ISSUE TITLE
 CreateDXGIFactory2 (dxgi.dll) error on startup (6.0)

### ISSUE THREAD

**Issue by Komprogue** [jurplel/qView#612]
I'm still using Windows 7 Pro x64 and have got this error on start of the ver. 6.0:

_The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll._

![csrss_la3eXNcH9R](https://github.com/jurplel/qView/assets/84424346/c7b2afef-d927-4aeb-bca9-bbcd73932808)

**Comment by GoD-Tony** [comment]
I don't think Qt6 supports Windows 7

**Comment by jurplel** [comment]
Correct. I need to update the website, thanks for the reminder. Try the 32-bit version, it's built with Qt5.

**Comment by gemkeeper** [comment]
——I understand. So, is it possible that after version 6.1, the WIN7-64 system will no longer be able to use the 64-bit version of qView, and can only use the 32-bit version?

That is to say, from now on, the 64 bit version of qView will no longer support Win7-64 bit systems?

**Comment by jurplel** [comment]
> That is to say, from now on, the 64 bit version of qView will no longer support Win7-64 bit systems?

Correct.
