### ISSUE TITLE
Error in installing qView to MacBook

### ISSUE THREAD

**Issue by timodahl** [jurplel/qView#615]
**Environment:**
- OS: BigSur 11.7.9
- qView version: 6.1 (I guess. The installation didn't start)

**Information:**
I got the installation file ok. But after starting it I got the error message: 
qView.app cannot be opened because Apple cannot scan it for malware. This software needs to be updated. Ask the developer for more information.

Br. Timo Dahlgrén
timo.dahlgren@gmail.com

**Comment by jurplel** [comment]
This isn't a real issue, it's because Apple wants developers to pay for their certification. Try right clicking it and press open.

**Comment by timodahl** [comment]
Thank you. I'll try.

**Comment by timodahl** [comment]
I made what you said. And now it works. :)  Thank you very much. Now I try it more.

**Comment by jurplel** [comment]
Glad to hear it.
