### ISSUE TITLE
6WIN7-64 system,  6.1 Press this button, after installation, open it and report an error:  QVier Exe cannot find entry  Unable to locate the program input point CreateDXGIFactory2 on the dynamic link library dxgi.d1l.  The 5.0 old version did not report this error

### ISSUE THREAD

**Issue by gemkeeper** [jurplel/qView#617]
WIN7-64 system,
6.1-64.exe Press this button, after installation, open it and report an error:

QVier Exe cannot find entry
Unable to locate the program input point CreateDXGIFactory2 on the dynamic link library dxgi.d1l.
————————
Install 6.1-32-bit. exe and open it. The system reports an error:
Computer system loss MSVCP140_ 1. DLL
——————————
The 5.0 -64.xexe old version did not report this error

**Comment by jdpurcell** [comment]
See #612

**Comment by jurplel** [comment]
>  Install 6.1-32-bit. exe and open it. The system reports an error:
Computer system loss MSVCP140_ 1. DLL

You need MSVC2015+, 32-bit
