### ISSUE TITLE
Request: Add ability to customize Pan/move to the middle mouse button

### ISSUE THREAD

**Issue by the01player** [jurplel/qView#619]
Coming from programs like Blender, Gimp, Krita, etc I am used to using the middle mouse button click to pan and move the image around, because in those programs the left click usually does something else like use a brush.

It would be awesome if qView let you customize how you pan the image, whether you want it to be left click, right click, or middle mouse click. 

Currently middle mouse click zooms an image to fit the window size, which I find useful but would probably change to right or left click if I could customize these options, and then use middle mouse to pan and move instead.

**Comment by jurplel** [comment]
I made a bigger issue for this
