### ISSUE TITLE
Keybind to reload the file from disk

### ISSUE THREAD

**Issue by brian6932** [jurplel/qView#624]
Smol convenience feature, would be nice to be able to reload the currently viewed file from disk, without having to go back and forward in gallery, maybe with `r` or `f5`

**Comment by jdpurcell** [comment]
Duplicate of #587. And I just went ahead and implemented it in PR #625! The default shortcut key is platform specific (e.g. F5 on Windows, Command-R on macOS), I didn't want to use `r` because I already used that for Go -> Random File in my fork.

**Comment by jurplel** [comment]
closing this because it's a duplicate. Thanks!
