### ISSUE TITLE
Copy to folder shortcut

### ISSUE THREAD

**Issue by IcyFoxe** [jurplel/qView#629]
What I'm really missing 
I used to , but now that its development has stopped 

I stumbled upon your app today and I really like how clean, fast and lighweight it is. It's a perfect replacement for Honeyview - image viewer that I was using before, but it has long ago stopped being developed.

Your app is amazing, however I'm missing one very useful feature, and that is **copy to folder** functionality, using a shortcut key.

In Honeyview you specified a path to a folder where you would like a copy of your currently viewed picture to be placed - not creating duplicated (so if you pressed the shortcut 3 times, you would have only 1 copy of the image in the folder). It's an amazing feature for sorting or picking out the best pictures of the bunch. I was using it all the time.

If you could add this feature to your app, that would me amazing and I would be very grateful!

**Comment by jurplel** [comment]
I think this could be implemented as part of https://github.com/jurplel/qView/issues/579, but not on its own. Closing as duplicate.

Thanks for the suggestion!
