### ISSUE TITLE
Can't make it work on my macbook

### ISSUE THREAD

**Issue by rileyzari** [jurplel/qView#633]
**Environment:**
- OS: macOS 13.5.1 Ventura (M1)
- qView version: qView-6.1.dmg (https://github.com/jurplel/qView/releases/download/6.1/qView-6.1.dmg)

**Information:**
I cannot make that work on my macOS machine. I get the following **error message**:

<img width="337" alt="Screenshot 2023-09-11 at 17 41 51" src="https://github.com/jurplel/qView/assets/144705675/77dd0a06-742b-4fc5-beb5-03a5aa18c6e3">

**Comment by jurplel** [comment]
Fix should be on this page:
https://iboysoft.com/howto/apple-cannot-check-it-for-malicious-software.html

I think this is the quarantine attribute IIRC. Not a qview bug--just macOS being overly excited.
