### ISSUE TITLE
Add an ability to go forwards/backwards using mouse

### ISSUE THREAD

**Issue by D0mika** [jurplel/qView#648]
Clicking on right/left side of the screen, like in default windows photo viewer, would open next/previous picture respectively

**Comment by vivadavid** [comment]
Related to this issue, I'd like to be able to go to the next or previous image using the mouse wheel. I tried to find this in the settings, but I didn't see it. Thanks for considering this!

**Comment by jurplel** [comment]
Sorry, I don't intend to add a feature like this for the foreseeable future.

> Related to this issue, I'd like to be able to go to the next or previous image using the mouse wheel. I tried to find this in the settings, but I didn't see it. Thanks for considering this!

This would be covered by the mega-issue on mouse button rebinding: https://github.com/jurplel/qView/issues/620
