### ISSUE TITLE
Investigate punctuation sorting nitpick

### ISSUE THREAD

**Issue by jurplel** [jurplel/qView#658]
Investigate using `setIgnorePunctuation` in collator to resolve issue.

Excerpt from discord:
> I didn't trunkate, this is just how nai names saved files: 'blue eyes, girl{military un s-3485643968.png',  'frown, blue eyes, girl{mili s-31189563.png', 'frown, blue eyes, girl{mili s-3145225707.png', 'frown, blue eyes, girl{{naz s-1585290273.png'. I open the first image in qview and it jumps straight to last one when I press next because of that extra curly brace.

**Comment by jurplel** [comment]
Existing attempt to look into this: https://github.com/jurplel/qView/issues/207

Might want to check consistency w/ other programs

**Comment by jdpurcell** [comment]
I'd say rather that whatever file manager showed the ordering as in the excerpt, is the odd man out. When I test with those exact names, Windows 11 Explorer, macOS 14 Finder, and Fedora 40 Dolphin are all showing the file with double curlies in the second position alphabetically. It could be something language-specific though.

**Comment by jurplel** [comment]
ok, ill trust your investigation and shelve this for now
