### ISSUE TITLE
ICC Profile when enabled, instantly crashes qView

### ISSUE THREAD

**Issue by brian6932** [jurplel/qView#662]
**Environment:**
- OS: Windows 10
- qView version: 6c7a99df1f776feea3200902c68be8ab53a36e7e 2023-12-27.1

**Information:**
ICC Profile https://github.com/jurplel/qView/files/14150800/AG271QG.-.RTINGS.zip <- mpv reports that this ICC Profile's too wide and can cause some clipping, instead of crashing
Seems to work fine with this one https://github.com/jurplel/qView/files/14150832/AG271QG.zip <- mpv doesn't report any such issues

**Comment by jdpurcell** [comment]
I can reproduce this. I believe it was an issue in Qt, although I'm not exactly sure when it was fixed, but the crash goes away when I try the more recent builds of my fork that use Qt 6.5.3 instead of 6.2.2.
