### ISSUE TITLE
dot-underscore file on macOS are in playback

### ISSUE THREAD

**Issue by yo1995** [jurplel/qView#664]
![image](https://github.com/jurplel/qView/assets/9660181/81f26c26-488e-44cb-9798-d1cf7b6f06c6)

**Environment:**

- OS: macOS 14.3
- qView version: 6.1

**Information:**

When files are copied over and opened on a flash drive, the "dot-underscore files" are created by macOS. They can be cleaned easily such as [`dot_clean`](https://ss64.com/mac/dot_clean.html), but it is kind of annoying to do that each time.

I dig into the code a bit and find the logic around this place it a bit incorrect.

https://github.com/jurplel/qView/blob/6c7a99df1f776feea3200902c68be8ab53a36e7e/src/qvimagecore.cpp#L273-L290

Ideally when the dot file are read, they should not be `matched`; however because the dot files also have `JPG` extension, the loop breaks early.

Maybe adjust the order of these conditions, or rewrite the logic a bit?

**Comment by jdpurcell** [comment]
@yo1995 The logic to ignore dot-underscore files was added after the qView 6.1 release, so it's only present in the nightly builds currently. You can try out the [build here](https://github.com/jurplel/qView/actions/runs/7342374798) which should work; it does for me at least.

**Comment by jurplel** [comment]
Yes looks to me like the feature is already implemented. Nice catch.
