### ISSUE TITLE
Crash when opening images on Windows 11

### ISSUE THREAD

**Issue by Soulusions** [jurplel/qView#694]
**Environment:**
- OS: Win11
- qView version: 6.1

**Information:**
Opening any image in qView results in a crash.
The errors happens in the Qt6Gui.dll at `0x00007ff8357a202a in Qt6Gui!?applyInverse@QColorTransferTable@@QEBAMMM@Z ()`

**Comment by jdpurcell** [comment]
Very likely related to #662. The fix for that isn't in an official release yet, but you could try a [CI build](https://github.com/jurplel/qView/actions/runs/9690993474).

**Comment by Soulusions** [comment]
Seems like that's what it was!
Thanks!
