### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by jasonchampagne** [jurplel/qView#697]
Hello, is there a configuration file for qView or is this planned for a future version?

**Comment by jdpurcell** [comment]
Currently the configuration is not in a file that can easily be edited. It's stored in a platform-specific manner, such as the Registry on Windows, or a binary .plist file on macOS.

If you'd like to view the saved configuration:
Windows: Use the Registry Editor and go to `HKEY_CURRENT_USER\SOFTWARE\qView\qView`
macOS: In Terminal, run `defaults read com.qview.qView`, or open ~/Library/Preferences/com.qview.qView.plist in Xcode

Example of changing settings via command line:
Windows: `reg add HKEY_CURRENT_USER\SOFTWARE\qView\qView\options /v loopfoldersenabled /f /t REG_SZ /d false`
macOS: `defaults write com.qview.qView options.loopfoldersenabled -bool FALSE`
