### ISSUE TITLE
Can't display a jpeg correctly

### ISSUE THREAD

**Issue by zwei7** [jurplel/qView#698]
**Environment:**
Windows 10 64 bit
qView version 6.1

**Information:**
Cannot view jpegs (1 jpeg out of 20 to 40 won't work) created by my Sony A6000 camera, it is not the camera or my sd cards since the jpegs work fine when open in photoshop, chrome, and firefox when I drag the jpeg over to each program. Surprisingly the Canon SX720 HS camera doesn't have this problem when using qView to view jpegs. Only qView 6.1 cannot open the problematic jpegs from a Sony A6000. Windows Explorer also can generate a thumbnail from it fine as well.

Below is 1 of the the problematic jpegs of many
Hopefully the jpeg isn't reprocessed
Here us the File CRC: FBC6AE66 to verify it is exact
![DSC07200](https://github.com/jurplel/qView/assets/15259298/85466da5-17c9-4d19-9e3a-f26a8ee91c92)

This is what shows up in qView 6.1, wrong resolution and white with some color noise
![2024-07-06 16_10_51-Greenshot](https://github.com/jurplel/qView/assets/15259298/d858ad18-6867-4d75-ba7d-db37e3fd31c7)

**Comment by jdpurcell** [comment]
@zwei7 Do you need/want the ability to open RAW files in qView? If not, try deleting kimg_raw.dll from qView's imageformats folder. I believe the RAW decoder is somehow claiming it can handle this file and preventing it from going through the proper JPEG decoder.

I will do some more troubleshooting and see if there is a way to fix / work around this in the code without sacrificing RAW support.

**Comment by zwei7** [comment]
Yes I would like to view raws. Hopefully you can find a solution. Thank you!
