### ISSUE TITLE
Attempting to open .psd files in the same directory when switching files using arrow keys

### ISSUE THREAD

**Issue by Creat55** [jurplel/qView#701]
**Environment:**
- OS: [windows 11]
- qView version: [6.1]

**Information:**
 When I use the arrow keys to switch files, qview attempts to open .psd files in the same directory.
![1720678746177](https://github.com/jurplel/qView/assets/64245796/e1c30415-e5b5-44f4-8ba4-51cf2968aa50)

**Comment by jurplel** [comment]
Right, they're meant to be supported but there are some issues with that. Should be addressed in https://github.com/jurplel/qView/issues/672
