### ISSUE TITLE
Support heif file extension on mac.

### ISSUE THREAD

**Issue by kimjj81** [jurplel/qView#702]
In mac, qview supports heif.
But it is not registered in support file extension on mac.
So If I want to heif image series, I must open it one by one.
Thanks.
<img width="598" alt="image" src="https://github.com/user-attachments/assets/b70d86f2-605b-4f0f-8c0a-23fdaed4710b">

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/78752bf0-b38c-4668-a2e7-22e45aed4dd1">

**Comment by jurplel** [comment]
The problem is that `.heif` is recognized but not `.hif`. Should be a simple fix to just insert `.hif` to the supported file extension list if `.heif` is present.
