### ISSUE TITLE
使用程序时发生程序卡死崩溃

### ISSUE THREAD

**Issue by SN626** [jurplel/qView#704]
**Environment:**
- OS: [Windows 10]
- qView version: [6.1]

**Information:**
我在使用qview查看大量的图片忽然出现卡死与崩溃，似乎是程序访问内存时出现了错误，但是在查看已经加载过的图片并没有问题，仅在尝试查看新图片时会出现崩溃现象
电脑的日志信息里似乎记录了问题，这或许对你们有些帮助？

故障存储段 2234182426799031677，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: qView.exe
P2: 6.1.0.0
P3: 64dc4c60
P4: Qt6Gui.dll
P5: 6.2.2.0
P6: 619d0ca0
P7: c0000005
P8: 000000000004202a
P9: 
P10: 

错误应用程序名称: qView.exe，版本: 6.1.0.0，时间戳: 0x64dc4c60
错误模块名称: Qt6Gui.dll，版本: 6.2.2.0，时间戳: 0x619d0ca0
异常代码: 0xc0000005
错误偏移量: 0x000000000004202a
错误进程 ID: 0x1ee0
错误应用程序启动时间: 0x01dae19715e02226
错误应用程序路径: d:\Program Files\qView\qView.exe
错误模块路径: d:\Program Files\qView\Qt6Gui.dll
报告 ID: 9410fc14-b1a0-49a1-b836-dc6857d63d29
错误程序包全名: 
错误程序包相对应用程序 ID: 

[qview-Application-1.txt](https://github.com/user-attachments/files/16410628/qview-Application-1.txt)
[qview-Application.txt](https://github.com/user-attachments/files/16410630/qview-Application.txt)

**Comment by jdpurcell** [comment]
Duplicate of #662
