### ISSUE TITLE
sony raw files *.arw don't open, when qt6-imageformats is installed

### ISSUE THREAD

**Issue by beihempels** [jurplel/qView#714]
**Environment:**
- OS: Arch Linux
- qView version: 6.1

**Information:**
"Unable to read image data (error 4)" is displayed, when opening an *.arw file.
When qt6-imageformats is not installed, it works.
Console output:
qt.imageformats.tiff: "Unknown field with tag 50341 (0xc4a5) encountered"
qt.imageformats.tiff: "TIFF directory is missing required \"ImageLength\" field"
QFSFileEngine::open: No file name specified

**Comment by jdpurcell** [comment]
This should be fixed after #700 gets merged.

**Comment by beihempels** [comment]
The error disappeared with qt6-imageformats 6.7.3-1 and now it opens the *.arw files. 
There is just the message: "QImageReader::size gave an invalid size for *.ARW, using size from loaded pixmap".

**Comment by jurplel** [comment]
hopefully fixed

> `QImageReader::size gave an invalid size for *.ARW, using size from loaded pixmap`
This is no cause for concern
