### ISSUE TITLE
MacOs 15 - qView quit unexpectedly

### ISSUE THREAD

**Issue by LaPinc3** [jurplel/qView#717]
Since updating to macOS 15, I’ve been encountering an error every time I close the qView application. Restarting my system hasn’t resolved the issue. I hope this gets addressed soon, as I can’t imagine switching to another app!
Keep up the excellent work!

![qview](https://github.com/user-attachments/assets/8712e338-940e-4d25-a6d9-d8a7e85d4bb8)

System:
MacBook Pro M1
MacOs Sequoia 15.0
qView 6.1

**Comment by LaPinc3** [comment]
Should we expect for the fix anytime soon?
Seems like most people who upgraded to MacOS 15 are experiencing this bug

**Comment by vassudanagunta** [comment]
I've was getting it on Sonora, so not just Sequoia.

**Comment by ndawod** [comment]
+1

**Comment by phamtony** [comment]
+1

**Comment by NotImportant1116** [comment]
Still happening almost 2 years later
