### ISSUE TITLE
Disable welcome page using Group Policy for windows users

### ISSUE THREAD

**Issue by Sslendyy** [jurplel/qView#721]
Hello,
I really like your program and it works wonderfully.
There is just one detail I would like to know whether it is possible or not.
I work in a terminal server environment for some application testing and I use the program to open image files, but my colleagues complained that every time we rebuild Windows Active Directory users the Welcome page always appears on the first start-up.
I wanted to know if there was any way I could prevent this from happening, perhaps through Group Policy or registry keys that I can change. 
Thank you very much.

**Comment by Sslendyy** [comment]
Looking inside the config of the program there is a registry key called "firstlaunch" and if you set the value to true the welcome page doesn't open anymore.
The path is: HKEY_CURRENT_USER\Software\qView\qView
Inside you create the key using group policy and set it to true. (It needs to be a user group policy and not a machine group policy)

**Comment by jurplel** [comment]
right, nicely found!
